akka/akka-management

- .travis.yml
- build.sbt
- cluster-http/src/main/resources/reference.conf
- cluster-http/src/main/scala/akka/management/cluster/http/ClusterHttpManagement.scala
- docs/src/main/paradox/index.md
- project/Common.scala
- project/Dependencies.scala
- project/Publish.scala
- project/build.properties
- project/plugins.sbt
Package name is anticipating future additions, such as stream management to a separate subproject.
> Initial structure

- .scalafmt.conf
- .travis.yml
- CONTRIBUTING.md
- README.md
- build.sbt
- cluster-http/src/main/scala/akka/cluster/http/management/ClusterHttpManagement.scala
- cluster-http/src/test/scala/akka/cluster/http/management/ClusterHttpManagementRoutesSpec.scala
- cluster-http/src/test/scala/akka/cluster/http/management/ClusterHttpManagementSpec.scala
- docs/src/main/paradox/cluster-builtin-management.md
- docs/src/main/paradox/cluster-http-management.md
- docs/src/main/paradox/index.md
- project/Common.scala
- project/Dependencies.scala
- project/plugins.sbt
> Preparation for the first release

- docs/src/main/paradox/cluster-http-management.md
Dependencies appeared to be incorrect. This addresses the issue reported here:
https://github.com/akka/akka-cluster-management/issues/15
> Fixed the dependency docs to point to the correct location.

- .travis.yml
- project/Dependencies.scala
> update akka, akka-http, scala dependencies, #19

- .travis.yml
- CONTRIBUTING.md
- README.md
- RELEASING.md
- build.sbt
- docs/src/main/paradox/index.md
- project/Common.scala
- project/Publish.scala
Resolves https://github.com/akka/akka-management/issues/10
> Change name to Akka Management

- build.sbt
- cluster-http-tests/src/test/scala/akka/cluster/http/management/MultiDcSpec.scala
- project/Dependencies.scala
- project/build.properties
* Test multi-dc works for akak 2.5.6 keeping main dep at 2.4
* Upgrade to sbt 0.13.16
* Upgrade to akka 2.4.20
0.4 was broken as it compared nodes from different DCs, this test will
fail if that is re-introduced
> Test multi-dc in a separate project

- build.sbt
- cluster-http/src/main/scala/akka/cluster/http/management/ClusterHttpManagement.scala
- cluster-http/src/test/scala/akka/cluster/http/management/ClusterHttpManagementRoutesSpec.scala
- cluster-http/src/test/scala/akka/cluster/http/management/MultiDcSpec.scala
- docs/src/main/paradox/cluster-http-management.md
- project/Dependencies.scala
* Removed the separate test project now master is at 2.5.6
* MultiDcSpec checks all nodes are up
> Upgrade to akka 2.5.6 and support multidc

- cluster-http/src/main/scala/akka/cluster/http/management/ClusterHttpManagement.scala
nice error message for when a shard region not responding (may happen after graceful shutdown)
> nice error message for when a shard region not responding (may happen after graceful shutdown)

- cluster-http/src/main/scala/akka/cluster/http/management/ClusterHttpManagement.scala
- cluster-http/src/test/scala/akka/cluster/http/management/ClusterHttpManagementRoutesSpec.scala
ticket: https://github.com/akka/akka-management/issues/45
PS: I've signed the CLA
> Respect pathprefix

- cluster-http/src/main/resources/reference.conf
- cluster-http/src/main/scala/akka/cluster/bootstrap/ClusterBootstrap.scala
- cluster-http/src/main/scala/akka/cluster/bootstrap/ClusterBootstrapSettings.scala
- cluster-http/src/main/scala/akka/cluster/bootstrap/contactpoint/HttpBootstrapJsonProtocol.scala
- cluster-http/src/main/scala/akka/cluster/bootstrap/contactpoint/HttpClusterBootstrapRoutes.scala
- cluster-http/src/main/scala/akka/cluster/bootstrap/dns/HeadlessServiceDnsBootstrap.scala
- cluster-http/src/main/scala/akka/cluster/bootstrap/dns/HttpContactPointBootstrap.scala
- cluster-http/src/main/scala/akka/cluster/http/management/ClusterHttpManagement.scala
- cluster-http/src/main/scala/akka/cluster/http/management/ClusterHttpManagementProtocol.scala
- cluster-http/src/main/scala/akka/cluster/http/management/ClusterHttpManagementRoutes.scala
- cluster-http/src/main/scala/akka/cluster/http/management/ClusterHttpManagementSettings.scala
- cluster-http/src/main/scala/akka/discovery/AkkaDnsServiceDiscovery.scala
- cluster-http/src/main/scala/akka/discovery/ServiceDiscovery.scala
- cluster-http/src/test/java/akka/cluster/http/management/ClusterHttpManagementJavaCompileTest.java
- cluster-http/src/test/scala/akka/cluster/bootstrap/contactpoint/ClusterBootstrapDnsHttpIntegrationSpec.scala
- cluster-http/src/test/scala/akka/cluster/bootstrap/contactpoint/HttpContactPointRoutesSpec.scala
- cluster-http/src/test/scala/akka/cluster/http/management/ClusterHttpManagementRoutesSpec.scala
- cluster-http/src/test/scala/akka/cluster/http/management/ClusterHttpManagementSpec.scala
- cluster-http/src/test/scala/akka/cluster/http/management/MultiDcSpec.scala
- cluster-http/src/test/scala/akka/discovery/MockDiscovery.scala
- docs/src/main/paradox/bootstrap.md
- docs/src/main/paradox/index.md
- joining-demo/build.sbt
- joining-demo/kubernetes/akka-cluster.yml
- joining-demo/src/main/resources/application.conf
- joining-demo/src/main/scala/akka/cluster/bootstrap/DemoApp.scala
- project/Common.scala
- project/Dependencies.scala
Resolves #55  and adds tests for joining as well as the routes.
Also some cleanups.
Please review (merge at will), will continue with more docs and may find some cleanups along the way tomorrow
> nodes now can figure out their address to join, even if random

- .travis.yml
- project/Whitesource.scala
- project/plugins.sbt
As our whitesource token is not available on external
PR's.
> Update whitesource, don't run on external pr's

- build.sbt
Resolves https://github.com/akka/akka-management/issues/74
> move akka-discovery one package up in groupid  #74

- discovery/src/main/scala/akka/discovery/ServiceDiscovery.scala
- discovery/src/test/resources/reference.conf
- discovery/src/test/scala/akka/discovery/DiscoveryConfigurationSpec.scala
> config using names instead of classnames actually works now #77

- docs/src/main/paradox/discovery.md
Minor improvement: in the code snippets, added a line that shows the usage of the `discovery.lookup(..) `method... Also, removed an empty line in the Java code snippet since it caused the code snippet to show malformed (it's an open bug in paradox actually).
Cheers!
> Docs: small improvement

- README.md
- docs/src/main/paradox/akka-management.md
Fixes #94 
Also fixes a broken link in the README page.
Cheers!
> Docs: fix issue with dependency

- README.md
- docs/src/main/paradox/akka-management.md
- docs/src/main/paradox/discovery.md
Found other places in the docs where issue #94 comes up.
Cheers!
> Docs: fix Scala version issue in dependencies

- bootstrap-joining-demo/aws-api/CloudFormation/akka-cluster.json
- bootstrap-joining-demo/aws-api/CloudFormation/akka-cluster.yaml
- bootstrap-joining-demo/aws-api/README.md
Add a simple cloud formation script (that automates the steps in the README.md tutorial).
Both .json and .yaml versions included (same script).
Cheers!
> AWS API bootstrap demo: add CloudFormation script 

- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/dns/HeadlessServiceDnsBootstrap.scala
- cluster-bootstrap/src/test/scala/akka/discovery/MockDiscovery.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/HttpContactPointRoutesSpec.scala
- cluster-http/src/test/scala/akka/cluster/http/management/MultiDcSpec.scala
- discovery/src/main/scala/akka/discovery/ServiceDiscovery.scala
- management/src/test/scala/akka/management/http/AkkaManagementHttpEndpointSpec.scala
> Remove unsued imports

- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrapSettings.scala
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/dns/HeadlessServiceDnsBootstrap.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapBasePathIntegrationSpec.scala
- management/src/main/resources/reference.conf
- management/src/main/scala/akka/management/AkkaManagement.scala
> Bootstrap respects base-path

- docs/src/main/paradox/akka-management.md
Fixes some serious formatting issue in the main doc page... See screenshots: [https://imgur.com/a/Y7buH](https://imgur.com/a/Y7buH)
> Docs: fix formatting issue

- docs/src/main/paradox/bootstrap.md
Doc improvement to talk about recommended configuration and member downing.
Fixes #109
> Mention shutdown-after-unsuccessful-join-seed-nodes and plug SBR

- bootstrap-joining-demo/marathon-api-docker/src/main/scala/akka/cluster/bootstrap/MarathonApiDockerDemoApp.scala
- build.sbt
@ktoso @longshorej I lost and haven't push necessary entry, since now it's a sub-module.
> Add missing marathon api docker demo build definition

- docs/src/main/paradox/akka-management.md
> Make hostname config documentation more accurate

- bootstrap-joining-demo/kubernetes-api/kubernetes/akka-cluster.yml
- bootstrap-joining-demo/kubernetes-api/project/build.properties
- bootstrap-joining-demo/kubernetes-api/src/main/resources/application.conf
Change management port according to deployment configuration.
> Change port configuration for contact point discovery #114

- discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/JsonFormat.scala
- discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala
- discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/PodList.scala
- discovery-kubernetes-api/src/test/resources/pods.json
- discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/JsonFormatSpec.scala
- discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscoverySpec.scala
> Kubernetes API discovery now ignores pods that are being terminated

- discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala
- docs/src/main/paradox/discovery.md
Fixes #137 
```
[ERROR] [02/23/2018 19:05:36.129] [my-system-akka.actor.default-dispatcher-2] [akka.actor.ActorSystemImpl(my-system)] Failed to unmarshal Kubernetes API response status [403 Forbidden]; check RBAC settings
[WARN] [02/23/2018 19:05:36.129] [my-system-akka.actor.default-dispatcher-16] [akka.tcp://my-system@172.17.0.6:10000/system/headlessServiceDnsBootstrap] Resolve attempt failed! Cause: spray.json.DeserializationException: Object is missing required member 'items'
```
```
[WARN] [02/23/2018 19:05:36.129] [my-system-akka.actor.default-dispatcher-16] [akka.tcp://my-system@172.17.0.6:10000/system/headlessServiceDnsBootstrap] Resolve attempt failed! Cause: spray.json.DeserializationException: Object is missing required member 'items'
[DEBUG] [02/23/2018 19:05:36.129] …
```
> Document Kubernetes RBAC usage and make debugging easier

- docs/src/main/paradox/bootstrap.md
before diving into the code I read the documentation and tried the demo :-)
> improve documentation

- docs/src/main/paradox/akka-management.md
> Add Akka version requirement #185

- bootstrap-joining-demo/marathon-api-docker/src/main/scala/akka/cluster/bootstrap/MarathonApiDockerDemoApp.scala
- build.sbt
Make sure we publish the new aggregate and config discoveries
Resolves https://github.com/akka/akka-management/issues/226
> include aggregate and config discoveries in root

- discovery/src/main/scala/akka/discovery/SimpleServiceDiscovery.scala
> better toString in ResolvedTarget

- bootstrap-joining-demo/kubernetes-api/kubernetes/akka-cluster.yml
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrap.scala
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/LowestAddressJoinDecider.scala
> Allow multiple 'self' addresses in cluster bootstrap

- docs/src/main/paradox/discovery.md
And drop trailing spaces from the end of lines
> Fix typos in the last commit

- bootstrap-joining-demo/kubernetes-api/kubernetes/akka-cluster.yml
> Add RBAC resources for bootstrap-joining-demo

- cluster-bootstrap/src/test/java/jdoc/akka/management/cluster/bootstrap/ClusterBootstrapCompileOnly.java
- cluster-bootstrap/src/test/scala/doc/akka/management/cluster/bootstrap/ClusterBootstrapCompileOnly.scala
- docs/src/main/paradox/bootstrap/details.md
- docs/src/main/paradox/bootstrap/examples.md
- docs/src/main/paradox/bootstrap/index.md
- docs/src/main/paradox/bootstrap/troubleshooting.md
- docs/src/main/paradox/cluster-http-management.md
- docs/src/main/paradox/discovery/index.md
- docs/src/main/paradox/index.md
* Keep details on a separate page
> User instructions for bootstrap

- cluster-bootstrap/src/main/resources/reference.conf
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrapSettings.scala
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinator.scala
- cluster-bootstrap/src/test/scala/akka/discovery/MockDiscovery.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapBasePathIntegrationSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapDiscoveryBackoffIntegrationSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapExistingSeedNodesSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapIntegrationSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapRetryUnreachableContactPointIntegrationSpec.scala
> Bootstrap support for portName and protocol

- discovery-dns/src/main/scala/akka/discovery/dns/DnsSimpleServiceDiscovery.scala
- discovery-dns/src/test/scala/akka/discovery/dns/DnsSimpleServiceDiscoverySpec.scala
- project/Dependencies.scala
Also includes commits from https://github.com/akka/akka-management/pull/274#pullrequestreview-148442323
> Additional records

- bootstrap-demo/aws-api-ec2/src/main/resources/application.conf
- bootstrap-demo/dns-api-mesos/src/main/resources/application.conf
- bootstrap-demo/kubernetes-api/src/main/resources/application.conf
- bootstrap-demo/kubernetes-dns/src/main/resources/application.conf
- bootstrap-demo/local/src/main/resources/application.conf
- bootstrap-demo/marathon-api-docker/src/main/resources/application.conf
- bootstrap-demo/marathon-api/src/main/resources/application.conf
- docs/src/main/paradox/bootstrap/index.md
- docs/src/main/paradox/bootstrap/kubernetes-api.md
- docs/src/main/paradox/bootstrap/local-config.md
> Show bootstrap-specific discovery mechanism

- cluster-http/src/main/scala/akka/management/cluster/ClusterHttpManagementHelper.scala
- cluster-http/src/main/scala/akka/management/cluster/ClusterHttpManagementProtocol.scala
- cluster-http/src/main/scala/akka/management/cluster/ClusterHttpManagementRoutes.scala
- cluster-http/src/test/scala/akka/cluster/http/management/ClusterHttpManagementHelperSpec.scala
- cluster-http/src/test/scala/akka/cluster/http/management/ClusterHttpManagementRoutesSpec.scala
> Expose oldest node per role

- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/LowestAddressJoinDecider.scala
> Warn when 'self' is not found in contact points

- project/build.properties
So it will compile when using java9
Refs #43
> Update sbt to 0.13.17

- bootstrap-demo/aws-api-ec2/README.md
- bootstrap-demo/kubernetes-api-java/build.sbt
- bootstrap-demo/kubernetes-api-java/kubernetes/akka-cluster.yml
- bootstrap-demo/kubernetes-api-java/project/build.properties
- bootstrap-demo/kubernetes-api-java/src/main/java/akka/cluster/bootstrap/demo/ClusterWatcher.java
- bootstrap-demo/kubernetes-api-java/src/main/java/akka/cluster/bootstrap/demo/DemoApp.java
- bootstrap-demo/kubernetes-api-java/src/main/resources/application.conf
- bootstrap-demo/kubernetes-api-java/src/main/resources/logback.xml
- bootstrap-demo/kubernetes-api-java/test.sh
- bootstrap-demo/kubernetes-api/src/main/resources/application.conf
- bootstrap-demo/kubernetes-api/src/main/scala/akka/cluster/bootstrap/DemoApp.scala
- bootstrap-demo/kubernetes-api/test.sh
- bootstrap-demo/marathon-api-docker/README.md
- bootstrap-demo/marathon-api/README.md
- build.sbt
- cluster-http/src/test/scala/akka/cluster/http/management/ClusterHttpManagementRoutesSpec.scala
- discovery-dns/src/test/scala/akka/cluster/bootstrap/discovery/DnsDiscoverySpec.scala
- docs/src/main/paradox/akka-management.md
- docs/src/main/paradox/bootstrap/index.md
- docs/src/main/paradox/cluster-http-management.md
- docs/src/main/paradox/discovery/index.md
- management/src/test/java/akka/management/http/CodeExamples.java
- management/src/test/scala/akka/management/http/AkkaManagementHttpEndpointSpec.scala
- management/src/test/scala/akka/management/http/CompileOnly.scala
> Extract sample code for docs

- bootstrap-demo/dns-api-mesos/src/main/scala/akka/cluster/bootstrap/DemoApp.scala
- bootstrap-demo/kubernetes-api/src/main/scala/akka/cluster/bootstrap/DemoApp.scala
- bootstrap-demo/kubernetes-dns/src/main/scala/akka/cluster/bootstrap/ClusterApp.scala
- bootstrap-demo/kubernetes-dns/src/main/scala/akka/cluster/bootstrap/NoisySingleton.scala
- discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala
because it gives better logger name
> replace system.log

- .travis.yml
- bootstrap-demo/kubernetes-api-java/kubernetes/akka-cluster.yml
- bootstrap-demo/kubernetes-api-java/src/main/resources/application.conf
- bootstrap-demo/kubernetes-api-java/test.sh
- bootstrap-demo/kubernetes-api/build.sbt
- bootstrap-demo/kubernetes-api/kubernetes/akka-cluster.yml
- bootstrap-demo/kubernetes-api/src/main/resources/application.conf
- bootstrap-demo/kubernetes-api/test.sh
- bootstrap-demo/kubernetes-dns/build.sbt
- bootstrap-demo/kubernetes-dns/kubernetes/akka-cluster.yml
- bootstrap-demo/kubernetes-dns/src/main/resources/application.conf
- bootstrap-demo/kubernetes-dns/test.sh
- build.sbt
- discovery-dns/src/main/resources/reference.conf
- discovery-kubernetes-api/src/main/resources/reference.conf
- docs/src/main/paradox/bootstrap/kubernetes-api.md
- docs/src/main/paradox/bootstrap/kubernetes.md
- docs/src/main/paradox/bootstrap/recipes.md
- Change to use a namespace for both minishift and minikube to make the
same resources work
Start of #365
> Document how to run kubernetes-api demo on open shift

- cluster-bootstrap/src/main/resources/reference.conf
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrap.scala
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrapSettings.scala
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/LowestAddressJoinDecider.scala
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/SelfAwareJoinDecider.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/AbstractBootstrapSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/ClusterBootstrapSettingsSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/LowestAddressJoinDeciderSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapExistingSeedNodesSpec.scala
- docs/src/main/paradox/bootstrap/details.md
- management/src/main/scala/akka/management/AkkaManagementSettings.scala
* Clarify usage of akka.management.cluster.bootstrap.form-new-cluster in code and documentation [351](https://github.com/akka/akka-management/issues/351)
* Added further testing 
* Minor cleanup of a test in cluster bootstrap
> Clarify usage of akka.management.cluster.bootstrap.form-new-cluster #351

- discovery-marathon-api/src/main/resources/reference.conf
- discovery-marathon-api/src/main/scala/akka/discovery/marathon/MarathonApiSimpleServiceDiscovery.scala
-Use the port name from the lookup if present, otherwise use it from the config
> Marathon Api port name (#370)

- bootstrap-demo/local/src/main/resources/application.conf
- cluster-bootstrap/src/main/resources/reference.conf
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/HttpContactPointBootstrap.scala
- docs/src/main/paradox/bootstrap/details.md
- docs/src/main/paradox/bootstrap/index.md
- docs/src/main/paradox/index.md
> De-dupe details and main bootstrap page + rolling update considerations

- docs/src/main/paradox/discovery/index.md
> EC2 tag based discovery: improve docs a bit wrt to privileges needed

- management/src/main/scala/akka/management/AkkaManagement.scala
This PR exposes the Akka Management router so that it can be served from
the same HTTP server as an existing application, eg, so that it can be
embedded in a Play/Lagom server. This means one less port for users to
understand and configure.
Rebased version of https://github.com/akka/akka-management/pull/414
> API to allow embedding routes in an existing server

- .jvmopts-travis
- .travis.yml
- bootstrap-demo/dns-api-mesos/build.sbt
- bootstrap-demo/kubernetes-api-java/pom.xml
- bootstrap-demo/marathon-api-docker/build.sbt
- bootstrap-demo/marathon-api/build.sbt
- project/Common.scala
- project/Dependencies.scala
Used https://github.com/akka/alpakka-kafka/blob/master/.travis.yml as template
> Adopt JDK 8 & 11, and Akka HTTP 10.1.6

- build.sbt
- management/src/main/scala/akka/management/AkkaManagement.scala
> check that all Akka Management modules have the same version, #425

- cluster-http/src/test/scala/akka/cluster/http/management/ClusterHttpManagementRoutesSpec.scala
- cluster-http/src/test/scala/akka/cluster/http/management/MultiDcSpec.scala
- docs/src/main/paradox/akka-management.md
- management/src/main/scala/akka/management/javadsl/AkkaManagement.scala
- management/src/main/scala/akka/management/javadsl/ManagementRouteProviderSettings.scala
- management/src/main/scala/akka/management/scaladsl/AkkaManagement.scala
- management/src/main/scala/akka/management/scaladsl/ManagementRouteProvider.scala
- management/src/main/scala/akka/management/scaladsl/ManagementRouteProviderSettings.scala
- management/src/test/java/akka/management/CodeExamples.java
- management/src/test/scala/akka/management/AkkaManagementHttpEndpointSpec.scala
- management/src/test/scala/akka/management/CompileOnly.scala
* overloaded start and routes methods with transformation function
to amend ManagementRouteProviderSettings
* javadsl was also missing for auth and HttpsConnectionContext
Refs #338 and more
> move auth and HttpsConnectionContext to ManagementRouteProviderSettings

- .travis.yml
- project/plugins.sbt
> Run whitesource with JDK8

- management/src/main/scala/akka/management/internal/HealthChecksImpl.scala
- management/src/main/scala/akka/management/javadsl/HealthChecks.scala
- management/src/main/scala/akka/management/scaladsl/HealthChecks.scala
- management/src/test/java/akka/management/HealthCheckTest.java
- management/src/test/scala/akka/management/HealthChecksSpec.scala
* To support Play/Lagom dependency injection into health checks.
Refs #457
> HealthChecks via ActorSystem setup, #457

- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/contactpoint/HttpBootstrapJsonProtocol.scala
- cluster-http/src/main/scala/akka/management/cluster/ClusterHttpManagementProtocol.scala
- cluster-http/src/test/scala/akka/management/cluster/scaladsl/ClusterMembershipCheckSpec.scala
- discovery-aws-api-async/src/main/scala/akka/discovery/awsapi/ecs/AsyncEcsServiceDiscovery.scala
- discovery-aws-api/src/main/scala/akka/discovery/awsapi/ecs/EcsServiceDiscovery.scala
- integration-test/aws-api-ec2/build.sbt
- management/src/main/scala/akka/management/internal/HealthChecksImpl.scala
- project/Common.scala
- project/Dependencies.scala
> Scala 2.13.0-M5 support

- integration-test/kubernetes-dns/src/main/resources/application.conf
- integration-test/scripts/kubernetes-test.sh
- project/Dependencies.scala
Mainly doing this to see the logs from DNS without setting it up locally
> Upgrade akka and log in int-tests on pass

- cluster-bootstrap/src/main/resources/reference.conf
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/LowestAddressJoinDeciderSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapBasePathIntegrationSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapDiscoveryBackoffIntegrationSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapExistingSeedNodesSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapIntegrationSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapRetryUnreachableContactPointIntegrationSpec.scala
- cluster-http/src/main/resources/reference.conf
- cluster-http/src/test/scala/akka/management/cluster/MultiDcSpec.scala
- docs/src/main/paradox/akka-management.md
- docs/src/main/paradox/bootstrap/recipes.md
- docs/src/main/paradox/cluster-http-management.md
- docs/src/main/paradox/healthchecks.md
- docs/src/main/paradox/migration.md
- integration-test/kubernetes-api-java/src/main/resources/application.conf
- integration-test/kubernetes-api/src/main/resources/application.conf
- integration-test/kubernetes-dns/src/main/resources/application.conf
- integration-test/local/src/main/resources/application.conf
- management/src/main/resources/reference.conf
- management/src/main/scala/akka/management/AkkaManagementSettings.scala
- management/src/main/scala/akka/management/HealthCheckSettings.scala
- management/src/main/scala/akka/management/scaladsl/AkkaManagement.scala
- management/src/test/scala/akka/management/AkkaManagementHttpEndpointSpec.scala
* to make it possible to disable route providers
* enable HealthCheckRoutes by default
Refs https://github.com/akka/akka-management/issues/470
> Change config structure for route providers, #470

- build.sbt
- docs/src/main/paradox/bootstrap/index.md
- integration-test/dns-api-mesos/README.md
- integration-test/dns-api-mesos/build.sbt
> update doc dependency of akka-discovery-dns, #463

- discovery-kubernetes-api/src/main/resources/reference.conf
- docs/src/main/paradox/discovery/kubernetes.md
Trying to clarify based on comments for question 2 in issue #464. Could you confirm if this is what you intended @TimMoore ?
Refs #464
> use  as port name, #464

- cluster-http/src/main/resources/reference.conf
As mentioned in https://github.com/akka/akka-management/issues/470#issuecomment-465004498
> Documents how to disable or replace the default cluster health check

- scripts/setup-minikube-for-linux.sh
> Allow using regular users to access the minikube client key

- docs/src/main/paradox/bootstrap/recipes.md
- integration-test/kubernetes-api-java/kubernetes/akka-cluster.yml
- integration-test/kubernetes-api-java/test.sh
- integration-test/kubernetes-api/kubernetes/akka-cluster.yml
- integration-test/kubernetes-api/test.sh
- integration-test/kubernetes-dns/test.sh
- integration-test/scripts/kubernetes-test.sh
> Clarify you need not have one namespace per Akka cluster (#408)

- cluster-http/src/test/scala/akka/management/cluster/MultiDcSpec.scala
> MultiDcSpec: Get free ports on the correct interface

- integration-test/local/src/test/scala/akka/management/LocalBootstrapTest.scala
> LocalBootstrapTest: Pick ports in one go to prevent already in use

- docs/src/main/paradox/bootstrap/kubernetes-api.md
Fixes https://github.com/akka/akka-management/issues/523
> Fix doc for kubernetes-api cluster bootstrap

- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/HttpContactPointBootstrap.scala
> Disable Akka HTTP retries in bootstrap probing

- discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/JsonFormat.scala
- discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscovery.scala
- discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/PodList.scala
- discovery-kubernetes-api/src/test/resources/pods.json
- discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/JsonFormatSpec.scala
- discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscoverySpec.scala
fix for https://github.com/akka/akka-management/issues/520
> Kubernetes discovery api: only consider running pods

- cluster-http/src/test/scala/akka/cluster/http/management/scaladsl/ClusterHttpManagementRoutesSpec.scala
> Widen test timeouts

- project/Dependencies.scala
Consul appears to use slf4j directly
> Enable logging when running consul tests

- discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscovery.scala
- discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscoverySpec.scala
Fixes #538
If no port is requested from kubernetes-api (because none is configured), it should just return one target per pod, with no port set.  Cluster bootstrap already falls back to using the configured Akka HTTP port if no port is returned from the lookup, so this will work.
I have tested this, and confirm it works (in particular, it works in an Istio environment where the ports can't be specified in the container spec).
> Don't return a port from kubernetes-api when none requested

- docs/src/main/paradox/.htaccess
https://github.com/akka/akka.github.com/issues/554
> Add .htaccess sample

- docs/release-train-issue-template.md
The minor version link needs to be updated on release.
https://github.com/lagom/lagom/pull/1966
> Release template: update the minor version link

- docs/src/main/paradox/healthchecks.md
> where as -> whereas

- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/HttpContactPointRoutesSpec.scala
Fix race for seeing cluster state updated
Fixes #493
> Harden: HttpContactPointRoutesSpec

- project/Dependencies.scala
https://github.com/akka/akka-http/issues/2612
> Update to Akka HTTP 10.1.9

- .travis.yml
> Publish with JDK8

- cluster-http/src/test/scala/akka/cluster/http/management/scaladsl/ClusterHttpManagementRoutesSpec.scala
Very minor https://github.com/akka/akka-management/issues/572, just something I added while looking at a related stats change in future.
> Minor test cleanup while looking at something related.

- docs/src/main/paradox/discovery/kubernetes.md
- integration-test/kubernetes-api-java/kubernetes/akka-cluster.yml
- integration-test/kubernetes-api/kubernetes/akka-cluster.yml
- integration-test/kubernetes-dns/kubernetes/akka-cluster.yml
Since apparently this is the way since K8s 1.9
> Use apiVersion apps/v1 for Deployment

- .travis.yml
The previous versions just don't work.
> Use wildcard minor version for jabba in travis

- docs/src/main/paradox/akka-management.md
https://github.com/akka/akka-http/issues/2710
> Fix link to authenticate directive

- project/Common.scala
> Target JDK8 for Java classes

- cluster-bootstrap/src/main/resources/reference.conf
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrapSettings.scala
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinator.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinatorSpec.scala
> Flag for disabling filter on fallback port

- README.md
- build.sbt
- docs/src/main/paradox/index.md
- docs/src/main/paradox/loglevels.md
- loglevels-logback/src/main/resources/reference.conf
- loglevels-logback/src/main/scala/akka/management/loglevels/logback/LogLevelRoutes.scala
- loglevels-logback/src/test/scala/akka/management/loglevels/logback/LogLevelRoutesSpec.scala
- project/Dependencies.scala
- project/project-info.conf
> Dynamic loglevel through management routes

- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/BootstrapLogMarker.scala
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrap.scala
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/LowestAddressJoinDecider.scala
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/SelfAwareJoinDecider.scala
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/contactpoint/HttpClusterBootstrapRoutes.scala
- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinator.scala
- docs/src/main/paradox/index.md
- integration-test/kubernetes-api-java/pom.xml
- management/src/main/scala/akka/management/ManagementLogMarker.scala
- management/src/main/scala/akka/management/internal/HealthChecksImpl.scala
- management/src/main/scala/akka/management/scaladsl/AkkaManagement.scala
- project/Dependencies.scala
> Structured log events for bootstrap, requires Akka 2.5.27, #629

- README.md
Fix the API link in Readme
thanks @johanandren for pointing me in the right direction.
> doc: Fix Api docs link in Readme

- docs/src/main/paradox/bootstrap/recipes.md
- docs/src/main/paradox/discovery/kubernetes.md
- integration-test/kubernetes-api-java/src/main/resources/application.conf
- integration-test/kubernetes-api/src/main/resources/application.conf
Since people prefer looking at code examples rather than reading bullet lists ;)
> Include bootstrap discovery method configuration in example

- project/plugins.sbt
In particular to get https://github.com/lightbend/sbt-whitesource/pull/59
and fix #651
Might supersede #652
> Update sbt-whitesource to 0.1.18

- docs/src/main/paradox/akka-management.md
> Link to how Lagom hooks into Coordinated shutdown

- build.sbt
- docs/src/main/paradox/akka-management.md
- docs/src/main/paradox/bootstrap/index.md
- docs/src/main/paradox/bootstrap/recipes.md
- docs/src/main/paradox/cluster-http-management.md
- docs/src/main/paradox/discovery/aws.md
- docs/src/main/paradox/discovery/consul.md
- docs/src/main/paradox/discovery/kubernetes.md
- docs/src/main/paradox/discovery/marathon.md
- docs/src/main/paradox/loglevels.md
> Docs: Clarify that it can be used with Akka 2.6

- docs/src/main/paradox/akka-management.md
- docs/src/main/paradox/bootstrap/index.md
- docs/src/main/paradox/bootstrap/recipes.md
- docs/src/main/paradox/cluster-http-management.md
- docs/src/main/paradox/discovery/aws.md
- docs/src/main/paradox/discovery/consul.md
- docs/src/main/paradox/discovery/kubernetes.md
- docs/src/main/paradox/discovery/marathon.md
- docs/src/main/paradox/loglevels.md
> Fix scala.binary.version references in docs

- .github/autolabeler.yml
- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
- .jvmopts-travis
- .travis.yml
- RELEASING.md
- docs/release-train-issue-template.md
- scripts/create-release-issue.sh
* revise release checklist and add script to create the issue
* configure release drafter via Github actions
* add PR autolabeler config
* introduce "integration" stage for Travis
> Simplify releasing

- docs/src/main/paradox/index.md
- docs/src/main/paradox/kubernetes-deployment/building-using-maven.md
- docs/src/main/paradox/kubernetes-deployment/building-using-sbt.md
- docs/src/main/paradox/kubernetes-deployment/building.md
- docs/src/main/paradox/kubernetes-deployment/deploying.md
- docs/src/main/paradox/kubernetes-deployment/forming-a-cluster.md
- docs/src/main/paradox/kubernetes-deployment/index.md
- docs/src/main/paradox/kubernetes-deployment/preparing-for-production.md
Also review PRs in the sample repos to make them follow the guide:
https://github.com/akka/akka-sample-cluster-kubernetes-java/pull/20
https://github.com/akka/akka-sample-cluster-kubernetes-scala/pull/24
> Deployment guide for Akka Cluster on Kubernetes

- .travis.yml
> Publish snapshot

- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrap.scala
- cluster-http/src/main/scala/akka/management/cluster/ClusterHttpManagementRouteProvider.scala
- discovery-consul/src/main/scala/akka/discovery/consul/ConsulSettings.scala
- discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/Settings.scala
- discovery-marathon-api/src/main/scala/akka/discovery/marathon/Settings.scala
- integration-test/kubernetes-api-java/pom.xml
- management/src/main/scala/akka/management/scaladsl/AkkaManagement.scala
- project/Dependencies.scala
> Update to Akka 2.5.31 and add ClassicActorSystemProvider in extensions, #298

- .travis.yml
- lease-kubernetes-int-test/src/main/scala/akka/coordination/lease/kubernetes/LeaseTestSuite.scala
https://github.com/akka/akka-management/issues/679
I expected that to be more work but easy given we already run other tests in minikube
> Lease tests in travis minikube

- project/Dependencies.scala
https://github.com/akka/akka-http/issues/3290
> build: use Akka 2.6 and Akka HTTP 10.2 in cron build

- project/Dependencies.scala
https://doc.akka.io/docs/akka-http/10.2/release-notes/10.2.x.html
> Akka HTTP 10.2 RC2 in the scheduled build

- .travis.yml
- integration-test/kubernetes-api-java/pom.xml
- integration-test/kubernetes-api-java/test.sh
- project/Dependencies.scala
Use the same versions for compilation and the tests in the Maven project.
> Akka HTTP 10.1.11 in Integration test Kubernetes API with maven

- .scala-steward.conf
> Scalasteward ignore scalatest and jackson

- cluster-bootstrap/src/test/resources/reference.conf
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/LowestAddressJoinDeciderSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapBasePathIntegrationSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapDiscoveryBackoffIntegrationSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapExistingSeedNodesSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapIntegrationSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapRetryUnreachableContactPointIntegrationSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/HttpContactPointRoutesSpec.scala
- cluster-http/src/main/scala/akka/management/cluster/scaladsl/ClusterHttpManagementRoutes.scala
- cluster-http/src/test/resources/application.conf
- cluster-http/src/test/scala/akka/cluster/http/management/scaladsl/ClusterHttpManagementRoutesSpec.scala
- cluster-http/src/test/scala/akka/management/cluster/MultiDcSpec.scala
- management/src/test/scala/akka/management/AkkaManagementHttpEndpointSpec.scala
- project/Dependencies.scala
> Use Akka 2.6 and Akka HTTP 10.2.0 in cron

- .travis.yml
> CI: skip the Maven-based test during scheduled builds

- docs/src/main/paradox/kubernetes-deployment/preparing-for-production.md
> Syntax error

- .scala-steward.conf
- project/Dependencies.scala
(It would be helpful to me in the Scala community build if this were merged.)
> move to JUnit 4.13

- docs/src/main/paradox/bootstrap/kubernetes-api.md
- integration-test/kubernetes-api/kubernetes/akka-cluster.yml
> Remove unnecessary info from YAML

- project/Dependencies.scala
> Consistent consul-client dependencies

- .travis.yml
- build.sbt
- cluster-bootstrap/src/main/mima-filters/1.0.8.backwards.excludes
- project/plugins.sbt
> Enable Mima on published projects

- cluster-http/src/main/scala/akka/management/cluster/scaladsl/ClusterHttpManagementRoutes.scala
- cluster-http/src/test/scala/akka/cluster/http/management/scaladsl/ClusterHttpManagementRoutesSpec.scala
- integration-test/aws-api-ec2/build.sbt
- integration-test/kubernetes-api/build.sbt
- integration-test/kubernetes-dns/build.sbt
- integration-test/marathon-api-docker/build.sbt
> cluster-http: support IPv6 addresses in cluster http routes

- docs/src/main/paradox/kubernetes-deployment/building-using-maven.md
Corresponding update of the sample https://github.com/akka/akka-sample-cluster-kubernetes-java/pull/24
> instructions of how to push image

- lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/internal/KubernetesApiImpl.scala
issue: https://github.com/akka/akka-management/issues/811
> Update KubernetesApiImpl.scala to prevent uppcase causing exception in k8s

- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/SelfAwareJoinDecider.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/LowestAddressJoinDeciderSpec.scala
References https://github.com/akka/akka-management/issues/795
> ignore [ and ] in host name when checking if a node can join itself

- integration-test/scripts/kubernetes-test.sh
Refs https://github.com/akka/akka-management/issues/767
> Kubernetes-test.sh: stop on first failure

- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapIntegrationSpec.scala
https://github.com/akka/akka-management/issues/785
> Get all the test's ports in one go to avoid conflicts

- docs/src/main/paradox/akka-management.md
> Fixed link to Coordinated Shutdown page

- lease-kubernetes/lease.yml
First round of minor improvements.
References #849
> minor Lease CRD improvement

- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrap.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapAutostartIntegrationSpec.scala
- docs/src/main/paradox/akka-management.md
- docs/src/main/paradox/bootstrap/index.md
> Autostart cluster bootstrap if the extension is loaded through config

- build.sbt
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapAutostartIntegrationSpec.scala
- cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapIntegrationSpec.scala
- project/Common.scala
> Increase timeout for failed boostrap, Test specific AS names

- docs/release-train-issue-template.md
- scripts/authors.scala
> Fix compilation errors on authors.scala

- .gitignore
- docs/src/main/paradox/kubernetes-lease.md
> Add link to SBR lease documentation; add .bsp to .gitignore

- cluster-http/src/main/scala/akka/management/cluster/scaladsl/ClusterHttpManagementRoutes.scala
- cluster-http/src/test/scala/akka/cluster/http/management/scaladsl/ClusterHttpManagementRoutesSpec.scala
- integration-test/kubernetes-api-java/pom.xml
- project/Dependencies.scala
Since we can now require Akka 2.6.14
Refs #830
> Remove now-unneeded reflection

- management/src/test/scala/akka/management/AkkaManagementHttpEndpointSpec.scala
> Remove ssl-config from test

- management/src/main/scala/akka/management/scaladsl/AkkaManagement.scala
References #847 . Support for default ipv6 address
> ipv6 default support

- docs/release-train-issue-template.md
To correctly describe we use GH Actions etc
> Update release checklist

- .github/workflows/integration-tests-kube-api.yml
- .github/workflows/integration-tests-kube-dns.yml
- .github/workflows/integration-tests-lease.yml
- .github/workflows/integration-tests-maven.yml
Use minikube action instead of a custom script.
> Fix integration tests

- management/src/main/scala/akka/management/scaladsl/AkkaManagement.scala
> Do not shutdown system materializer

- .scala-steward.conf
- project/Dependencies.scala
> Don't auto-update jackson-datatype

- docs/src/main/paradox/kubernetes-deployment/deploying.md
> typo in kubectl cmd in deployment guide

- .github/workflows/release-drafter.yml
- project/build.properties
> build: security updates

- build.sbt
- docs/src/main/paradox/index.md
- docs/src/main/paradox/loglevels/index.md
- docs/src/main/paradox/loglevels/log4j2.md
- docs/src/main/paradox/loglevels/logback.md
- loglevels-log4j2/src/main/resources/reference.conf
- loglevels-log4j2/src/main/scala/akka/management/loglevels/log4j2/LogLevelRoutes.scala
- loglevels-log4j2/src/test/scala/akka/management/loglevels/log4j2/LogLevelRoutesSpec.scala
- project/Dependencies.scala
- project/project-info.conf
Support for changing log levels when application is using log4j2 as backend.
> Support for log4j2 log levels

- docs/release-train-issue-template.md
No more whitespace, master->main
> Update release procedure

- project/Dependencies.scala
> latest akka-http version

- .github/workflows/release.yml
* matching current cross version
> Use Scala 2.13.8 for publishRsync

- CONTRIBUTING.md
- LICENSE
- project/Common.scala
https://www.lightbend.com/blog/why-we-are-changing-the-license-for-akka
> Change license

- cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/SelfAwareJoinDecider.scala
- cluster-bootstrap/src/test/scala/akka/discovery/MockDiscovery.scala
- discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscovery.scala
- discovery-marathon-api/src/main/scala/akka/discovery/marathon/MarathonApiServiceDiscovery.scala
- lease-kubernetes-int-test/src/main/scala/akka/coordination/lease/kubernetes/LeaseSpec.scala
- lease-kubernetes/src/it/scala/akka/coordination/lease/kubernetes/KubernetesApiIntegrationTest.scala
- lease-kubernetes/src/it/scala/akka/coordination/lease/kubernetes/LeaseContentionSpec.scala
- lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/KubernetesLease.scala
- lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/internal/KubernetesApiImpl.scala
- lease-kubernetes/src/test/scala/akka/coordination/lease/kubernetes/KubernetesApiSpec.scala
- management/src/main/scala/akka/management/scaladsl/AkkaManagement.scala
Run blocking on DefaultBlockingDispatcherId, similar to the rolling updates initialisation.
> chore: Blocking IO at startup

- docs/src/main/paradox/rolling-updates.md
- integration-test/rollingupdate-kubernetes/kubernetes/akka-cluster-app-value-revision.yml
- rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/KubernetesApi.scala
- rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/KubernetesApiImpl.scala
* pods is in core "" api group
* replicasets is in "apps" api group
> doc: Correction of rbac api group for AppVersionRevision

- docs/src/main/paradox/akka-management.md
- docs/src/main/paradox/bootstrap/index.md
- docs/src/main/paradox/bootstrap/recipes.md
- docs/src/main/paradox/cluster-http-management.md
- docs/src/main/paradox/discovery/aws.md
- docs/src/main/paradox/discovery/consul.md
- docs/src/main/paradox/discovery/kubernetes.md
- docs/src/main/paradox/discovery/marathon.md
- docs/src/main/paradox/kubernetes-deployment/forming-a-cluster.md
- docs/src/main/paradox/kubernetes-lease.md
- docs/src/main/paradox/loglevels/log4j2.md
- docs/src/main/paradox/loglevels/logback.md
- docs/src/main/paradox/rolling-updates.md
Reverts akka/akka-management#1189
> Revert "docs: Repository tag had a sneaky space"

- docs/src/main/paradox/bootstrap/recipes.md
> Fix a typo

- project/Common.scala
- project/Dependencies.scala
- project/project-info.conf
See https://github.com/akka/akka/pull/32125
> chore: Drop Scala 2.12

- integration-test/dns-api-mesos/build.sbt
- integration-test/kubernetes-api-java/pom.xml
- integration-test/marathon-api-docker/build.sbt
- integration-test/marathon-api/build.sbt
- project/Dependencies.scala
> bump: Akka 2.9.0

- .github/workflows/integration-tests-app-version-revision.yml
- .github/workflows/integration-tests-kube-api.yml
- .github/workflows/integration-tests-kube-dns.yml
- .github/workflows/integration-tests-lease.yml
- .github/workflows/integration-tests-maven.yml
- .github/workflows/integration-tests-rollingupdate-cr.yml
- .github/workflows/integration-tests-rollingupdate.yml
- integration-test/rollingupdate-kubernetes/build.sbt
- integration-test/rollingupdate-kubernetes/kubernetes/akka-cluster-cr.yml
- integration-test/scripts/app-version-revision-kubernetes-test.sh
- integration-test/scripts/kubernetes-test.sh
- integration-test/scripts/rollingupdate-kubernetes-cr-test.sh
- integration-test/scripts/rollingupdate-kubernetes-test.sh
* failing in CI
* I think it should wait for ready, not only running
* more error diagnostics
* jdk 17 image (seems to work)
* but main issue is the resource requuests with minikube
- argh, how many times are we going to run into this problem?
* update minikube and kubernetes versions
> test: Harden rollingupdate-kubernetes-cr-test.sh

- cluster-http/src/main/scala/akka/management/cluster/scaladsl/ClusterHttpManagementRoutes.scala
References https://discuss.lightbend.com/t/use-akka-management-with-typed-cluster/10604
> feat: Create ClusterHttpManagementRoutes with typed actor system

- LICENSE
References https://github.com/akka/akka-management/issues/1265
> chore: License change date for 1.5.1

- integration-test/kubernetes-api-java/pom.xml
- integration-test/marathon-api-docker/build.sbt
- integration-test/marathon-api/build.sbt
- native-image-tests/build.sbt
- samples/akka-sample-cluster-kubernetes-java/pom.xml
- samples/akka-sample-cluster-kubernetes-scala/build.sbt
I missed a few.
References https://github.com/akka/akka-management/issues/1289
> bump: Some more test and sample bumps

- native-image-tests/src/main/scala/com/lightbend/Main.scala
Follow up to https://github.com/akka/akka-management/pull/1303
> fix: init revisionAnnotation in KubernetesJsonSupport in native spec

- docs/src/main/paradox/migration.md
> Fix typo - close markdown backquote

- .scala-steward.conf
- integration-test/aws-api-ec2/build.sbt
- project/Dependencies.scala
See https://github.com/akka/akka/pull/32705
> bump: Jackson 2.18.3

- LICENSE
- samples/akka-sample-cluster-kubernetes-java/pom.xml
- samples/akka-sample-cluster-kubernetes-scala/build.sbt
References https://github.com/akka/akka-management/issues/1386
> chore: License change date and samples bump for 1.6.1

- LICENSE
- samples/akka-sample-cluster-kubernetes-java/pom.xml
- samples/akka-sample-cluster-kubernetes-scala/build.sbt
References https://github.com/akka/akka-management/issues/1389
> chore: License change and sample bump for 1.6.2

- .github/workflows/checks.yml
- .github/workflows/integration-tests-app-version-revision.yml
- .github/workflows/integration-tests-kube-api.yml
- .github/workflows/integration-tests-kube-dns.yml
- .github/workflows/integration-tests-lease.yml
- .github/workflows/integration-tests-maven.yml
- .github/workflows/integration-tests-rolling-update-cr.yml
- .github/workflows/integration-tests-rolling-update.yml
- .github/workflows/integration-tests-samples.yml
- .github/workflows/link-validator.yml
- .github/workflows/native-image-tests.yml
- .github/workflows/release.yml
- .github/workflows/unit-tests.yml
- akka.sbt
- project/plugins.sbt
Will update the CI to place the credential a follow up commit.
> chore: replace akka resolver
