akka/akka-management

build.sbt
project/Publish.scala

Also generate 2.12 style links to scaladoc (2.11 supports 2.12 links as well, surprisingly).

Do no publish root and docs projects

---

README.md

instead of specifying a specific version

Use link to "current" documentation

---

cluster-http/src/main/resources/reference.conf
cluster-http/src/main/scala/akka/cluster/http/management/ClusterHttpManagementSettings.scala

Default hostname to InetAddress.getLocalHost.getHostAddress() when left empty ""..
[Issue link](https://github.com/akka/akka-cluster-management/issues/11)

default hostname to InetAddress.getLocalHost.getHostAddress()

---

cluster-http/src/main/scala/akka/cluster/http/management/ClusterHttpManagement.scala
cluster-http/src/test/scala/akka/cluster/http/management/ClusterHttpManagementRoutesSpec.scala
docs/src/main/paradox/cluster-http-management.md
project/Dependencies.scala

Fixes https://github.com/akka/akka-management/issues/14
This PR exposes the `GET /shards/{name}` path, which returns the following data:
```
{
regions: [
{
"shardId": // shard id [string]
"numEntities": // number of entities in the shard [int]
},
...
]
]
```
At eero, we use this information in the following ways
* monitoring: check the health of an akka cluster instance (example: did it lose shards all of a sudden?)
* deploys: after deploying new code to an akka cluster instance, we wait for it to attain shards before deploying the next instance
One change to note is that commit e7ff9c7 changes how the `prefix` works. Before, `prefix` would override the `members` path. Now, if `prefix` is set, it will be a prefix to `members` and `shard_regions`

Expose Shard Details

---

cluster-http/src/test/scala/akka/cluster/http/management/ClusterHttpManagementSpec.scala
project/Dependencies.scala

Also removed warnings generated while compiling **ClusterHttpManagementSpec.scala**
**Here's an example:**
Warning:(192, 38) postfix operator seconds should be enabled
by making the implicit value scala.language.postfixOps visible.
This can be achieved by adding the import clause 'import scala.language.postfixOps'
or by setting the compiler option -language:postfixOps.
See the Scaladoc for value scala.language.postfixOps for a discussion
why the feature should be explicitly enabled.
Await.ready(bindingFuture, 5 seconds)

Updated spray-json library dependency from 1.3.2 to 1.3.3

---

cluster-http/src/main/scala/akka/cluster/http/management/ClusterHttpManagement.scala
cluster-http/src/test/scala/akka/cluster/http/management/ClusterHttpManagementRoutesSpec.scala
docs/src/main/paradox/cluster-http-management.md

This PR should resolve issue #28 by eliminating the requirement to have `akka.tcp://` in the URI. Instead you could just use `application@host:1234` to identify a member.

Making the akka.tcp:// part in URI optional

---

cluster-http/src/main/resources/reference.conf

Per https://github.com/akka/akka-management/blob/master/cluster-http/src/main/scala/akka/cluster/bootstrap/ClusterBootstrapSettings.scala#L35
should be `effective-name`, not `effective-service-name`

Fix mispelled effective-name key

---

build.sbt
discovery-kubernetes-api/src/main/resources/reference.conf
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/JsonFormat.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/PodList.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/Settings.scala
discovery-kubernetes-api/src/test/resources/pods.json
discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/JsonFormatSpec.scala
discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscoverySpec.scala
docs/src/main/paradox/discovery.md
project/Dependencies.scala

This adds a K8s-API based implementation of `SimpleServiceDiscovery`. By using this (instead of the DNS one), the cluster can bootstrap itself before passing its readiness checks.

Discovery implementation based on Kubernetes API

---

discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala
discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscoverySpec.scala

This fixes a bug in the Kubernetes discovery API. `targets` shouldn't be filtering by container name as that is the job of the configured selector, which out of the box defaults to `app=<actor-system-name>`
Thus, this PR allows containers with different names to join the same cluster if configured with an appropriate selector.
For instance, given `-Dakka.discovery.kubernetes-api.pod-label-selector=actorSystemName=my-system`, any pods that specify `label: { "actorSystemName": "my-system" }` will now be returned by the k8s service discovery module.
Note that this was the original intent but filtering by name in `targets` was included by oversight.
I've tested this locally with a custom project of two different applications and will be publishing said project shortly.
**Update: Here's said …

Remove filter for k8s pod names as that is done by the selector

---

discovery-aws-api/src/main/resources/reference.conf
discovery-aws-api/src/main/scala/akka/discovery/awsapi/ec2/Ec2TagBasedSimpleServiceDiscovery.scala
docs/src/main/paradox/discovery.md

This allows the user to add additional filters to the tag based discovery. For example, you usually may want to subset by region or some tag that indicates the environment (test, production etc.). This is optional though.

Discovery: EC2 Tag Based - now can support additional filters

---

build.sbt
discovery-marathon-api/src/main/resources/reference.conf
discovery-marathon-api/src/main/scala/akka/discovery/marathon/AppList.scala
discovery-marathon-api/src/main/scala/akka/discovery/marathon/JsonFormat.scala
discovery-marathon-api/src/main/scala/akka/discovery/marathon/MarathonApiSimpleServiceDiscovery.scala
discovery-marathon-api/src/main/scala/akka/discovery/marathon/Settings.scala
discovery-marathon-api/src/test/resources/apps.json
discovery-marathon-api/src/test/scala/akka/discovery/marathon/MarathonApiSimpleServiceDiscoverySpec.scala
docs/src/main/paradox/discovery.md
project/Dependencies.scala

This adds another discovery mechanism, this time for Marathon. This allows you to discover other nodes for the bootstrapping process while also defining health checks. It also allows you to take advantage of DC/OS's dynamic port declarations.
I've verified this with an example I'm preparing in another repository. I'll try to clean it up and submit it as an example in this repo via a follow-up PR.

Discovery mechanism for Marathon API

---

docs/src/main/paradox/akka-management.md
management/src/main/resources/reference.conf
management/src/main/scala/akka/management/AkkaManagement.scala
management/src/main/scala/akka/management/AkkaManagementSettings.scala

In order to support network bridge mode on Mesosphere, had to introduce bind-hostname to be able bind to interface within container, but still be able to address it externally and compare it with the list of seed nodes provided by bootstrap.
It solves the issue described in https://github.com/akka/akka-management/issues/64

Mesos bridge mode support

---

management/src/main/scala/akka/management/AkkaManagement.scala

Fixes #91 
Enabled programatically so as to not affect other HTTP servers (that may not want it enabled).

Enable remote address header for akka management server

---

bootstrap-joining-demo/marathon-api/README.md
bootstrap-joining-demo/marathon-api/build.sbt
bootstrap-joining-demo/marathon-api/marathon/app.json
bootstrap-joining-demo/marathon-api/project/build.properties
bootstrap-joining-demo/marathon-api/project/plugins.sbt
bootstrap-joining-demo/marathon-api/src/main/resources/application.conf
bootstrap-joining-demo/marathon-api/src/main/scala/akka/cluster/bootstrap/DemoApp.scala

Adds an example for #98. Example won't work until a release is done with that PR in (version used is 0.8.1 below, can change if released with different version)

Add example for using Marathon API

---

cluster-bootstrap/src/main/resources/reference.conf
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrapSettings.scala
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/dns/HeadlessServiceDnsBootstrap.scala
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/dns/HttpContactPointBootstrap.scala
docs/src/main/paradox/bootstrap.md

This a setting, `allow-formation` which when disabled will prevent a new cluster from being formed, i.e. it will only attempt to join others.
Fixes #95

Add setting to prevent a new cluster from being formed

---

.gitignore
bootstrap-joining-demo/marathon-api-docker/README.md
bootstrap-joining-demo/marathon-api-docker/build.sbt
bootstrap-joining-demo/marathon-api-docker/marathon/marathon-api-docker-app.json
bootstrap-joining-demo/marathon-api-docker/project/build.properties
bootstrap-joining-demo/marathon-api-docker/project/plugins.sbt
bootstrap-joining-demo/marathon-api-docker/src/main/resources/application.conf
bootstrap-joining-demo/marathon-api-docker/src/main/scala/akka/cluster/bootstrap/DemoApp.scala
discovery-marathon-api/src/main/scala/akka/discovery/marathon/AppList.scala
discovery-marathon-api/src/main/scala/akka/discovery/marathon/JsonFormat.scala
discovery-marathon-api/src/main/scala/akka/discovery/marathon/MarathonApiSimpleServiceDiscovery.scala
discovery-marathon-api/src/test/resources/docker-app.json
discovery-marathon-api/src/test/scala/akka/discovery/marathon/MarathonApiSimpleServiceDiscoverySpec.scala
version.sbt

@longshorej I added Docker support. When a docker container selected, a port name declaration placed in different location of an application description: `apps/contatiner/docker/portMappings`

marathon-api add docker-support

---

docs/src/main/paradox/bootstrap.md

Title says it all. Several config properties were incorrectly listed under `akka.cluster` when they actually exist under `akka.management.cluster`.

corrected some invalid config property names in the docs

---

cluster-bootstrap/src/main/resources/reference.conf
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrapSettings.scala
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/dns/HeadlessServiceDnsBootstrap.scala
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/dns/HttpContactPointBootstrap.scala
cluster-bootstrap/src/test/scala/akka/discovery/MockDiscovery.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapBasePathIntegrationSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapRetryUnreachableContactPointIntegrationSpec.scala

#105 
In the first step, discovery service returns non-empty list of contact point nodes, even if these nodes are unreachable, bootstrap won't request it ever again, but will keep trying.
This change makes it escalate repeating connection error and initiate rediscovery if probing keep resulting with failure for the some period of time as specified in `probing-failure-timeout`

Re-discover when contact point probing fails 

---

bootstrap-joining-demo/marathon-api-docker/build.sbt
bootstrap-joining-demo/marathon-api-docker/marathon/marathon-api-docker-app.json
bootstrap-joining-demo/marathon-api-docker/src/main/scala/akka/cluster/bootstrap/MarathonApiDockerDemoApp.scala
bootstrap-joining-demo/marathon-api/build.sbt
bootstrap-joining-demo/marathon-api/marathon/app.json
bootstrap-joining-demo/marathon-api/src/main/resources/application.conf
bootstrap-joining-demo/marathon-api/src/main/scala/akka/cluster/bootstrap/DemoApp.scala

This improves the Marathon demos:
* Adds health/readiness checks based on cluster status.
* Sets `minimumHealthCapcity` and `maximumOverCapacity` to values recommended by Mesosphere for stateful applications: https://mesosphere.github.io/marathon/docs/persistent-volumes.html#upgradingrestarting-stateful-applications
* Sets `"killSelection": "YOUNGEST_FIRST"` as well which is particularly important for singletons during a deployment.
This results in these demos being much more reliable when restarting applications.
/cc @mitkus

Improve marathon demos, adding health/readiness checks

---

discovery-aws-api/src/main/scala/akka/discovery/awsapi/ec2/Ec2TagBasedSimpleServiceDiscovery.scala

RIght now if no filters are defined, and default value `""` is used it will fail with `java.lang.AssertionError: assertion failed: failed to parse one of the key-value pairs in filters`

Make akka.discovery.aws-api-ec2-tag-based.filters optional

---

discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/JsonFormat.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/PodList.scala
discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/JsonFormatSpec.scala
discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscoverySpec.scala

* Fixes the Kubernetes discovery to be inline with the types defined by the K8s docs, notably several fields made optional
* Renames the local types to what they're actually named in the K8s docs
* Some logging improvements to help debug failures
Fixes #147

Kubernetes discovery debugability / parsing improvements

---

build.sbt

Issue found as follows:
1. I try updating Liquidity to 0.11.0 now that it's been released.
Uh oh:
```
sbt:liquidity> update
[info] Updating server
[info] Resolved server dependencies
[error] coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     com.lightbend.akka.discovery:akka-discovery-aws-api-async_2.12:0.11.0:
[error]         not found:
[error]             /home/david/.ivy2/local/com.lightbend.akka.discovery/akka-discovery-aws-api-async_2.12/0.11.0/ivys/ivy.xml
[error]             https://repo1.maven.org/maven2/com/lightbend/akka/discovery/akka-discovery-aws-api-async_2.12/0.11.0/akka-discovery-aws-api-async_2.12-0.11.0.pom
[error] (server / coursierResolutions) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error] …
```

Fix aws-api-async not being built/published

---

cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinator.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala

**Problem**
When you use `kubernetes-api` as a discovery mechanism, and the property `pod-label-selector` is different from `effective-name`, you will see in the logs still `effective-name` being used (while it's not the case *only* with kubernetes-api). 
**Solution**
The solution proposed here is to remove `effective-name` from the logged statement. Then, once we retrieve the Resolved points, we can log the service-name used to locate the members. For this reason, we also need to change what `KubernetesApiSimpleServiceDiscovery.lookup` returns, because it doesn't return a Resolved object with `serviceName=pod-label-selector` but  `serviceName=effective-name`. I think this is a good trade-off, because we don't lose the log (which may be useful).
This is a fix for …

Fix log inconsistency when using kubernetes-api

---

discovery-aws-api/src/main/scala/akka/discovery/awsapi/ec2/Ec2TagBasedSimpleServiceDiscovery.scala

The `withFilters` method of AWS' `DescribeInstancesRequest` is always a set operation when used with a collection. Ec2TagBasedSimpleServiceDiscovery chains calls to withFilters and ends the chain by passing a collection to the method, which effectively drops all filters previously set.
This change merges all ec2 filters in a single java list before building the `DescribeInstancesRequest`.
Closes https://github.com/akka/akka-management/issues/177.

Fixed aws-api ec2 use of filters

---

LICENSE

Would resolve #195 
I copied this from the akka/akka repository, left out the final lines about protobuf. I understand that I am not a project member therefore I am not sure if it is acceptable to have my name on this change. Please decline if necessary.

Add full Apache 2 license from main akka repo

---

discovery-marathon-api/src/main/scala/akka/discovery/marathon/MarathonApiSimpleServiceDiscovery.scala

We added a bit more verbosity to the system logs if debug is enabled, as well as print out full object if serialization failure...

additional logging info

---

discovery-aws-api-async/src/main/scala/akka/discovery/awsapi/ecs/AsyncEcsSimpleServiceDiscovery.scala
discovery-aws-api/src/main/scala/akka/discovery/awsapi/ec2/Ec2TagBasedSimpleServiceDiscovery.scala
discovery-aws-api/src/main/scala/akka/discovery/awsapi/ecs/EcsSimpleServiceDiscovery.scala

As our service discovery should throttle down its pace of calling APIs, this moves the control outside about retries outside of the AmazonEC2Client.
Fixes #193

Disable AmazonEC2Client's retries

---

docs/src/main/paradox/discovery.md

Adds a small note for GKE users, fixes #199.
/cc @dbrinegar @mitkus

Add note on GKE permissions for k8s-api discovery

---

build.sbt
cluster-bootstrap/src/main/resources/reference.conf
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrapSettings.scala
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinator.scala
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/HttpContactPointBootstrap.scala
cluster-bootstrap/src/test/scala/akka/discovery/MockDiscovery.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapBasePathIntegrationSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapDiscoveryBackoffIntegrationSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapRetryUnreachableContactPointIntegrationSpec.scala

Will resolve https://github.com/akka/akka-management/issues/193 I'd hope.
It makes the timeouts more staggered as well as implements a backoff on failure

implement backoff in discovery usage in bootstrap #193

---

docs/src/main/paradox/bootstrap.md

This PR fixes the paths of the `required-contact-point-nr` to match the reference.conf as described in #210

update the path of required-contact-point-nr to match the reference.conf

---

discovery-kubernetes-api/src/main/resources/reference.conf
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/Settings.scala
discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscoverySpec.scala

Istio service mesh requires that every service (e.g. bootstrap contact points) be requested by name (not by ip-addr).
Pods are assigned a DNS A record in the form of “**pod-ip-address**.my-namespace.**pod**.cluster.local”. [see](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods)
This is a simple implementation for k8s pod lookup by name.

k8s pod lookup by name (#209)

---

discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala

Fixes https://github.com/akka/akka-management/issues/222
The `Revolved` record expects the service name, but the Kubernetes API discovery's `Resolved` record currently returns the label selector instead of the queried service name.
This causes Lagom to fail on startup on Kubernetes with a strange error.
```
akka.actor.ActorSystemImpl [sourceThread=application-akka.actor.default-dispatcher-3, akkaTimestamp=xxxx, akkaSource=akka.actor.ActorSystemImpl(application), sourceActorSystem=application]
- Kubernetes API entity: [{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"found '=', expected: ',' or 'end of string'","reason":"BadRequest","code":400}
```
This is likely caused by querying  `app=app=foo`.

Fixes Kubernetes API Revolved value

---

cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/LowestAddressJoinDecider.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/LowestAddressJoinDeciderSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapBasePathIntegrationSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapDiscoveryBackoffIntegrationSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapIntegrationSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapRetryUnreachableContactPointIntegrationSpec.scala
discovery-aggregate/src/test/scala/akka/discovery/aggregate/AggregateSimpleServiceDiscoverySpec.scala
discovery-aws-api-async/src/main/scala/akka/discovery/awsapi/ecs/AsyncEcsSimpleServiceDiscovery.scala
discovery-aws-api/src/main/scala/akka/discovery/awsapi/ec2/Ec2TagBasedSimpleServiceDiscovery.scala
discovery-aws-api/src/main/scala/akka/discovery/awsapi/ecs/EcsSimpleServiceDiscovery.scala
discovery-config/src/main/scala/akka/discovery/config/ConfigSimpleServiceDiscovery.scala
discovery-config/src/test/scala/akka/discovery/config/ConfigServicesParserSpec.scala
discovery-config/src/test/scala/akka/discovery/config/ConfigSimpleServiceDiscoverySpec.scala
discovery-consul/src/main/scala/akka/discovery/consul/ConsulSimpleServiceDiscovery.scala
discovery-consul/src/test/scala/akka/cluster/bootstrap/discovery/ConsulDiscoverySpec.scala
discovery-dns/src/main/scala/akka/discovery/dns/DnsSimpleServiceDiscovery.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala
discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscoverySpec.scala
discovery-marathon-api/src/main/scala/akka/discovery/marathon/MarathonApiSimpleServiceDiscovery.scala
discovery-marathon-api/src/test/scala/akka/discovery/marathon/MarathonApiSimpleServiceDiscoverySpec.scala
discovery/src/main/scala/akka/discovery/SimpleServiceDiscovery.scala

Ref #187
#217 started returning “pod-ip-address.my-namespace.pod.cluster.local” in `ResolvedTarget` for Kubernetes API Discovery.
#236 reports that this is in conflict with Cluster Bootstrap when the "self" address is still based on an IP address.
This attempts to provide a fix for the situation by returning both the host name and an optional IP address in `ResolvedTarget`, and letting `LowestAddressJoinDecider` match on either the host or the address.

Allow an IP address to be used for the lowest "address"

---

cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/LowestAddressJoinDecider.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/LowestAddressJoinDeciderSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapBasePathIntegrationSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapDiscoveryBackoffIntegrationSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapIntegrationSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapRetryUnreachableContactPointIntegrationSpec.scala
discovery-aws-api-async/src/main/scala/akka/discovery/awsapi/ecs/AsyncEcsSimpleServiceDiscovery.scala
discovery-aws-api/src/main/scala/akka/discovery/awsapi/ec2/Ec2TagBasedSimpleServiceDiscovery.scala
discovery-aws-api/src/main/scala/akka/discovery/awsapi/ecs/EcsSimpleServiceDiscovery.scala
discovery-consul/src/main/scala/akka/discovery/consul/ConsulSimpleServiceDiscovery.scala
discovery-consul/src/test/scala/akka/cluster/bootstrap/discovery/ConsulDiscoverySpec.scala
discovery-dns/src/main/scala/akka/discovery/dns/DnsSimpleServiceDiscovery.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala
discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscoverySpec.scala
discovery-marathon-api/src/main/scala/akka/discovery/marathon/MarathonApiSimpleServiceDiscovery.scala
discovery-marathon-api/src/test/scala/akka/discovery/marathon/MarathonApiSimpleServiceDiscoverySpec.scala
discovery/src/main/scala/akka/discovery/SimpleServiceDiscovery.scala

This is a refinement on #242 a part of a fix towards #187
This brings `apply(String, Option[Int])` back as a factory method for `ResolvedTarget`, and changes the type of `address` to `java.net.InetAddress`.
Since various orchestration engines just return a String for "host", I am doing a quick regex check to make sure it looks like an IPv4 address, and then parsing it into an
`InetAddress`.

Use InetAddress type to denote IPv4 address

---

cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapDiscoveryBackoffIntegrationSpec.scala

Both actor systems can enter discovery at the same time.
So an update to the called volatile variable could be lost meaning
that it would time between the wrong calls.
Fixes #239

Fix race condition in ClusterBootstrapDiscoveryBackoffIntegrationSpec

---

docs/src/main/paradox/discovery.md

Because people may be running their akka service in docker on EC2, and
it isn't obvious in that section how to configure that.

Link to host/bind IP configuration from AWS EC2 section

---

cluster-http/src/test/java/jdoc/akka/cluster/http/management/CompileOnlyTest.java
cluster-http/src/test/scala/doc/akka/cluster/http/management/CompileOnlySpec.scala
docs/src/main/paradox/cluster-http-management.md

I got sufficiently stuck on this today that I thought it was worth writing docs for.
(Partially?) fixes #232

Clarify the way to start ClusterHTTPManagement

---

management/src/main/scala/akka/management/AkkaManagement.scala

When I call `akka.management.AkkaManagement#stop` in my project it always fails with `java.lang.ClassCastException: akka.Done$ cannot be cast to scala.runtime.BoxedUnit`. In the project I use `10.1.1` and I can not downgrade to `10.0`. In `10.1` `akka.http.scaladsl.Http.ServerBinding#unbind` returns `Future[Done]`, but in `10.0`, which is `akka-management` compiled with, it returns `Future[Unit]`, what causes problems.

Fix ClassCastException on stop when use akka-http 10.1

---

cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/contactpoint/HttpClusterBootstrapRoutes.scala

Akka Cluster Bootstrap should response only reachable nodes that are in status "up".

Bootstrap: should be done only with reachable nodes that are "up", "weaklyUp" or "joining"

---

discovery-marathon-api/src/main/scala/akka/discovery/marathon/MarathonApiSimpleServiceDiscovery.scala

This is driven by the real use case that took lots of time to debug. This setting was set during automatic deployment process and was pointing to the wrong Marathon master. It led to the situation when the app was joining different Akka Cluster from completely different environment.

Improve Marathon API logging to see where and how seed nodes have been requested.

---

project/Dependencies.scala

Some subprojects that depend on akka-testkit do not also depend on akka-http-testkit.

Split akka-http-testkit from the AkkaTesting group

---

bootstrap-demo/kubernetes-api/kubernetes/akka-cluster.yml
bootstrap-demo/kubernetes-api/src/main/resources/application.conf
bootstrap-demo/kubernetes-api/src/main/resources/logback.xml
bootstrap-demo/kubernetes-api/src/main/scala/akka/cluster/bootstrap/DemoApp.scala
bootstrap-demo/kubernetes-dns/src/main/scala/akka/cluster/bootstrap/KubernetesHealthChecks.scala
bootstrap-demo/local/src/main/scala/akka/cluster/bootstrap/Main.scala
build.sbt
discovery-kubernetes-api/src/main/resources/reference.conf
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala
docs/src/main/paradox/bootstrap/kubernetes-api.md
project/Dependencies.scala

Addresses a few gotchas when @alanngai was trying bootstrap
* Lookup contains a port, use that and fallback to the one in config
* Pick up namespace from environment variable if present
* Add some more logging to k8s api

Kubernetes API to take port from Lookup

---

.travis.yml
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/LowestAddressJoinDeciderSpec.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala
discovery/src/main/scala/akka/discovery/SimpleServiceDiscovery.scala

Workaround for #344
This might not have the desired effect when there are multiple routers with
different IP addresses doing name-based routing, and the service discovery
returns those with unique names but also addresses that point to those routers.
Perhaps we should cross that bridge when we know it appears in practice though.

Order addresses by address, then name

---

bootstrap-demo/aws-api-ec2/README.md
bootstrap-demo/aws-api-ec2/src/main/resources/CloudFormation/akka-cluster.json
bootstrap-demo/aws-api-ecs/README.md
bootstrap-demo/aws-api-ecs/cfn-templates/ecs-bootstrap-demo-app.yaml
bootstrap-demo/aws-api-ecs/scripts/publish.sh
bootstrap-demo/dns-api-mesos/README.md
bootstrap-demo/dns-api-mesos/build.sbt
bootstrap-demo/dns-api-mesos/marathon/app.bridge-mode.json
bootstrap-demo/dns-api-mesos/marathon/app.host-mode.json
bootstrap-demo/marathon-api-docker/README.md
bootstrap-demo/marathon-api-docker/build.sbt
bootstrap-demo/marathon-api-docker/marathon/marathon-api-docker-app.json
bootstrap-demo/marathon-api/README.md
bootstrap-demo/marathon-api/build.sbt
bootstrap-demo/marathon-api/marathon/app.json
discovery-marathon-api/src/test/resources/docker-app.json
docs/src/main/paradox/discovery/index.md
integration-test-scripts/aws-api-ec2-tag-based.sh

I started from find bad link in documentation. 
Found all places where "bootstrap-joining-demo" is set and fix names to "bootstrap-demo".
If you need any updates, please let me know.

Replace `bootstrap-joining-demo` to `bootstrap-demo` 

---

cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrap.scala

Rather than duplicating the logic of loading a discovery mechanism
Fixes #368

Use Servicedisocvery.load in bootstrap

---

docs/src/main/paradox/index.md

Fixes #379 
Started out with only the support status, ideas where to add recommended service discovery mechanisms welcome.

Note support status in docs

---

discovery/src/main/scala/akka/discovery/ServiceDiscovery.scala
discovery/src/test/scala/akka/discovery/DiscoveryConfigurationSpec.scala

- the underlying discovery mechanisms can throw exception related to their configuration, the exception is swallowed in recover with, causing confusion
Addresses the issue: #165

Discovery Service Additional Logging

---

discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala

* Don't unmarshal the response for non-200 status codes
* Specific log message for 403
* Log body at error for non-200 so users don't need to turn on DEBUG
Fixes #371

 Improve logging for kubernetes API communication issues

---

discovery/src/main/scala/akka/discovery/SimpleServiceDiscovery.scala
discovery/src/test/scala/akka/discovery/LookupSpec.scala

This will be handy when creating a Lagom `ServiceLocator` backed by Akka `ServiceDiscovery`. 
Lagom's `ServiceLocator` doesn't support port name and protocol. An easy way to work this around is to configure Lagom to lookup for a full SRV string, eg: `_cassandra._tpc.my-cassandra-instance`.
Before calling the underlying `ServiceDiscovery`, Lagom's `ServiceLocator` can build a SRV Lookup using that string. 
This can obviously be used in other situations as well (not included in this PR). For instances, `SimpleServiceDiscovery.lookup(serviceName: String, resolveTimeout: FiniteDuration)` could use the parser automatically. 
Current impl: 
```scala 
def lookup(serviceName: String, resolveTimeout: FiniteDuration): Future[Resolved] =
lookup(Lookup(serviceName), resolveTimeout)
```
Alternatively: …

Adds a parser to generate SRV Lookups from SRV strings

---

bootstrap-demo/kubernetes-api/src/main/scala/akka/cluster/bootstrap/DemoApp.scala
build.sbt
cluster-http/src/main/scala/akka/management/cluster/ClusterHttpManagementProtocol.scala
cluster-http/src/main/scala/akka/management/cluster/ClusterHttpManagementRoutes.scala
cluster-http/src/main/scala/akka/management/cluster/javadsl/ClusterHttpManagementRoutes.scala
cluster-http/src/test/java/jdoc/akka/cluster/http/management/CompileOnlyTest.java
cluster-http/src/test/scala/doc/akka/cluster/http/management/CompileOnlySpec.scala
docs/src/main/paradox/cluster-http-management.md

* Add javadsl for accessing the routes
* Correct how to use Cluster HTTP
* Document how to use the routes outside of Akka management

Expose routes so read only can be used in isolation

---

bootstrap-demo/kubernetes-api/src/main/resources/application.conf
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrap.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala

Closes #343 
Results in a log like:
```
11/23 10:08:50 INFO [Appka-akka.actor.default-dispatcher-2] a.d.k.KubernetesApiSimpleServiceDiscovery - Querying for pods with label selector: [app=akka-bootstrap-demo]. Namespace: [akka-bootstrap]. Port: [doh] (from lookup? true)                                                                                                                                                                                                   
11/23 10:08:51 INFO [Appka-akka.actor.default-dispatcher-18] a.d.k.KubernetesApiSimpleServiceDiscovery - No targets found from pod list. Is the correct port name configured? Current configuration: [doh]. Ports on pods: [Set(ContainerPort(Some(remoting),2552), ContainerPort(Some(management),8558), ContainerPort(Some(http),8080))] …
```

Useful error message if pod name misconfigured

---

project/Dependencies.scala

It is brought in by Akka in a binary compatible way
Closes #398

Remove dependency on java-scala-compat

---

bootstrap-demo/aws-api-ec2/README.md
bootstrap-demo/aws-api-ec2/src/main/resources/CloudFormation/akka-cluster.json
discovery-aws-api/src/main/resources/reference.conf
discovery-aws-api/src/main/scala/akka/discovery/awsapi/ec2/Ec2TagBasedSimpleServiceDiscovery.scala

Hopefully, the proper fix for  #377
**Note**: Tested against real AWS environment via the integration testing script .

EC2 tag based discovery: no longer block on default dispatcher

---

.travis.yml

As we use the one from Jabba anyway, and openjdk8 is no longer available on the Xenial images
Should fix #340

Don't specify travis JDK

---

bootstrap-demo/kubernetes-api-java/kubernetes/akka-cluster.yml
bootstrap-demo/kubernetes-api/kubernetes/akka-cluster.yml
discovery-kubernetes-api/src/main/resources/reference.conf
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiSimpleServiceDiscovery.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/Settings.scala
docs/src/main/paradox/bootstrap/kubernetes-api.md

Fixes #345
This also changes the api token lookup so it's read once using blocking
IO at startup, rather than on every request.
Rebased version of https://github.com/akka/akka-management/pull/413

Implemented Kubernetes namespace discovery

---

CONTRIBUTING.md

Clarify that contributors are expected to fork the project, and clarify that
creating a ticket up-front is not a requirement but might be smart for larger
ideas.

Small improvements to CONTRIBUTING.md

---

cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrap.scala
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrapSettings.scala
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/LowestAddressJoinDecider.scala
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/SelfAwareJoinDecider.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/ClusterBootstrapSettingsSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/LowestAddressJoinDeciderSpec.scala

Fixes #424.
Issue #238 introduced a hack that meant that cluster bootstrap used the pod host name when the kubernetes configuration was present, rather than the IP address, since Kubernetes discovery returned host names rather than IP addresses to work with Istio. That hack was made redundant however by #242, which introduced matching by either hostname, or IP address, so it didn't matter if the self host name was an IP address or hostname. However, the hack wasn't removed and stayed there, benign, until #415 changed the way namespace configuration is consumed. At that point, the hack was still benign, but resulted in some confusing log messages. This removes the hack.

Removed Kubernetes self contact points hack

---

docs/src/main/paradox/migration.md

Fix typo in migration guide

---

integration-test/aws-api-ecs/cfn-templates/ecs-integration-test-app-infrastructure.yaml
integration-test/aws-api-ecs/cfn-templates/ecs-integration-test-app.yaml
integration-test/aws-api-ecs/scripts/deploy-infrastructure.sh
integration-test/aws-api-ecs/scripts/deploy.sh
integration-test/aws-api-ecs/scripts/publish.sh

There were issues running the `aws-api-ecs` integration test, because the application name wasn't modified correctly.
Added all the required changes, and tested it.

Renaming "ecs-bootstrap-demo-app" to "ecs-integration-test-app"

---

project/Dependencies.scala

It was already effectively using 1.3.5 in the build, due to a transitive dependency from akka-http-spray-json. However, the published POM included the 1.3.3 dependency, causing downstream artifacts depending on Akka Management to resolve this incorrectly.
See https://github.com/lagom/lagom/pull/1454 for example.

Update spray-json dependency to 1.3.5

---

discovery-kubernetes-api/src/test/resources/pods.json
discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/JsonFormatSpec.scala
discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscoverySpec.scala
discovery-marathon-api/src/test/resources/apps.json
discovery-marathon-api/src/test/scala/akka/discovery/marathon/MarathonApiServiceDiscoverySpec.scala

We are now standardizing on 'management'. It should make no difference
for these tests, but might save some confusion.

Don't use akka-mgmt-http in tests anymore

---

cluster-bootstrap/src/main/resources/reference.conf
integration-test/dns-api-mesos/src/main/resources/application.conf
integration-test/kubernetes-api-java/kubernetes/akka-cluster.yml
integration-test/kubernetes-api-java/src/main/resources/application.conf
integration-test/kubernetes-api-java/test.sh
integration-test/kubernetes-api/kubernetes/akka-cluster.yml
integration-test/kubernetes-api/src/main/resources/application.conf
integration-test/kubernetes-dns/kubernetes/akka-cluster.yml
integration-test/kubernetes-dns/src/main/resources/application.conf

By passing it in as an environment variable, the values that should line up for
bootstrap to be successful are all in the deployment .yml, instead of being
spread across the deployment .yml and the packaged application.conf.
Refs #411

Pass in bootstrap service name through environment variable

---

management/src/main/scala/akka/management/scaladsl/AkkaManagement.scala

Currently Akka Management does not support specifying `base-path` with slashes. They are accepted (no exceptions are thrown), but URL-escaped to `%2F` under the hood. My company has specific rules, which determine how paths for internal service endpoints should look like. And these rules have slashes. So this PR adds possibility to define any `base-path`, with our without slashes, while maintaining full backwards compatibility.

Allow setting base path with slashes

---

discovery-kubernetes-api/src/main/resources/reference.conf
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscovery.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/Settings.scala
discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscoverySpec.scala
docs/src/main/paradox/discovery/kubernetes.md
integration-test/scripts/kubernetes-test.sh

It does not make sense to configure a default at this level. It might make
sense to configure a default at the cluster-bootstrap level.
If no port name is specified in the query, return all ports.
Simplification triggered by the discussion in #464

Remove pod-port-name option from kubernetes-api discovery

---

cluster-bootstrap/src/main/resources/reference.conf
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrapSettings.scala
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinator.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapBasePathIntegrationSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapDiscoveryBackoffIntegrationSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapRetryUnreachableContactPointIntegrationSpec.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinatorSpec.scala
integration-test/kubernetes-api-java/kubernetes/akka-cluster.yml
integration-test/kubernetes-api/kubernetes/akka-cluster.yml
integration-test/kubernetes-dns/kubernetes/akka-cluster.yml
integration-test/local/src/test/scala/akka/management/LocalBootstrapTest.scala

Refs #464: Instead of discovering by port name 'management', avoid a
named port lookup.
When multiple results are found, disambiguate based on 
the `fallback-port` which by default is populated with
`akka-management.http.port`.
This arguably makes discovery on Kubernetes a bit easier, since the
akka-management port does not need to be named any specific way in the
deployment .yml.
On the other hand, it makes the actual bootstrap/discovery process a bit
more complicated and thus harder to explain or troubleshoot.
I'm not convinced the convenience of not having to declare the port name in
the Kubernetes case weighs up to the extra complexity in the
bootstrap/discovery logic.

By default assume akka-management.http.port for bootstrap

---

docs/src/main/paradox/migration.md

Fix typo mananagement -> management

---

build.sbt
project/Common.scala

Add a meaningfu project description.
Add Scaladoc link support for Akka HTTP.
https://github.com/akka/akka.github.com/issues/568

Add description (which ends up in docs headers)

---

management/src/main/scala/akka/management/scaladsl/AkkaManagement.scala
management/src/test/scala/akka/management/AkkaManagementHttpEndpointSpec.scala

Fix for https://github.com/akka/akka-management/issues/525

Return bound port when port was randomly selected

---

docs/src/main/paradox/discovery/aws.md

Fix broken links in the AWS discovery document.
Each API type has its own page now.

Fix links to discovery methods from the AWS document

---

docs/src/main/paradox/bootstrap/index.md
docs/src/main/paradox/bootstrap/istio.md
docs/src/main/paradox/bootstrap/recipes.md

Istio 1.2.0 was released 2 days ago with the outbound port exclusion feature, so we can now support it.

Added Istio documentation

---

.travis.yml

should fix failure seen at https://travis-ci.org/akka/akka-management/builds/546627026

Be more flexible in what jabba jdk to use for whitesource

---

.travis.yml

Broke in Travis CI - missing `~` in `- JDK="adopt@~1.11.0-1"`

Added ~ to adopt jdk version prefix.

---

docs/src/main/paradox/bootstrap/kubernetes-api.md
docs/src/main/paradox/discovery/kubernetes.md
integration-test/kubernetes-api-java/kubernetes/akka-cluster.yml
integration-test/kubernetes-api/kubernetes/akka-cluster.yml

This is much simpler from a configuration perspective as it doesn't require understanding the service account user name string format, and it also allows the namespace to default to the namespace that the role binding is deployed to, which is usually what you want, and so means that role binding yaml specs can be used as is regardless of which namespace they are deployed to.
One caveat, I could not find any documentation on what should happen when no namespace is specified. Intuitively, it should use the namespace the role binding is deployed to, and I have confirmed through experimentation that this appears to be the case. I've raised this issue to get this documented:
https://github.com/kubernetes/website/issues/14624

Use ServiceAccount subject kind rather than user

---

build.sbt
project/Common.scala
project/Dependencies.scala

* Upgrades to Scala 2.12.10
* Uses the new Scaladoc flags introduced in 2.12.9 and 2.13.0 for better links to source and adding canonical URLs
References https://github.com/akka/akka.github.com/issues/623

Scaladoc: make use of new flags

---

cluster-bootstrap/src/main/resources/reference.conf
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinator.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinatorSpec.scala

Related to:
* https://github.com/akka/akka-management/issues/542
* https://github.com/akka/akka-management/pull/552
The behavior/description of setting the fallback-port for cluster-bootstrap is unexpected in the case of having multiple `ResolvedTarget` with the same host but no port defined.
Currently, the fallback-port will actually filter out all the found hosts.
I changed this, in the case of not a single defined port, to use the fallback-port.

Fix fallback port behavior on multiple resolved targets

---

cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrap.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/InactiveBootstrapSpec.scala

This allows to have the cluster-bootstrap module on the classpath without
actually configuring it. The management routes automatically instantiate
ClusterBootstrap when on the classpath. This fails when discovery is not
configured.
Fixes #519.

bootstrap: access discovery lazily in ClusterBootstrap extension

---

discovery-aws-api-async/src/main/resources/reference.conf
discovery-aws-api-async/src/main/scala/akka/discovery/awsapi/ecs/AsyncEcsDiscovery.scala
discovery-aws-api-async/src/main/scala/akka/discovery/awsapi/ecs/AsyncEcsServiceDiscovery.scala
discovery-aws-api-async/src/main/scala/akka/discovery/awsapi/ecs/AsyncEcsTaskSetDiscovery.scala
docs/src/main/paradox/discovery/aws.md
integration-test/aws-api-ecs/src/main/scala/akka/cluster/bootstrap/EcsApiDemoApp.scala
project/Dependencies.scala

Add a new discovery method for Akka in ECS Fargate using TaskSets.
1. Add `aws-api-ecs-task-set-async`
2. Update aws docs
3. Tested on our own instances using AWS CodeDeploy
ECS can be used together with AWS CodeDeploy to support blue/green deployments.
These new nodes are spawned in the same service-group. Therefore, we need a new approach to make sure nodes only form a cluster with only newly spawned nodes.
Otherwise, the new nodes will join the existing AkkaCluster forming 1 large cluster instead of 2 smaller ones.

Use TaskSets to discover nodes in ECS

---

cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrap.scala
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/SelfAwareJoinDecider.scala
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinator.scala
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/internal/HttpContactPointBootstrap.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/internal/BootstrapCoordinatorSpec.scala

Fixes #603 
When bootstrapping, all nodes must necessarily use the same URL scheme for bootstrapping endpoints, either HTTP or HTTPS. Otherwise, the nodes that use HTTP do not see the nodes that use HTTPS, and vice versa.
Currently, the URL scheme is hard-coded to `"http"` which makes nodes that expose their endpoints via HTTPS uncontactable. This pull request makes it so that contact points will be contacted with the same scheme of the node's own base URL. That is, if the own node exposes it's management enpoints via HTTPS, then other nodes will also be contacted via HTTPS. This is based on the premise that the scheme must be uniform.
PS: I don't think this is a "backwards incompatible change" because change only affects cluster-bootstrap deployments that use HTTPS. But in the current …

Uniform URL scheme for bootstrap URLs

---

.travis.yml

To avoid secenarios where the master build failure goes undetected.

Build failure notification

---

discovery-kubernetes-api/src/main/resources/reference.conf
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscovery.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/Settings.scala
discovery-kubernetes-api/src/test/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscoverySpec.scala

Enables the usage of the dotted IP address string as the host name, rather than relying on Kube's pod DNS scheme.

Kubernetes: Opt in to ip instead of host

---

management/src/main/scala/akka/management/HealthCheckRoutes.scala
management/src/main/scala/akka/management/internal/HealthChecksImpl.scala
management/src/main/scala/akka/management/javadsl/HealthChecks.scala
management/src/main/scala/akka/management/scaladsl/HealthChecks.scala
management/src/test/java/akka/management/HealthCheckTest.java
management/src/test/scala/akka/management/HealthCheckRoutesSpec.scala
management/src/test/scala/akka/management/HealthChecksSpec.scala

Include failing check name in health/readiness check messages/responses
This modifies the readiness/health check internals to ensure that when a check fails, for any reason, that the check's class name is included in the message to aid in debugging. Additionally, timeouts are now tracked on a per-check basis so that it's clear which check timed out.
~I haven't updated the tests yet -- if I could get some validation/assurance that such a chance would be accepted, then I'd be happy to get the tests passing.~
*Ready for a review.*
Example failure:
```
$ curl  192.168.1.20:8558/ready
Health Check Failed: Check [com.myco.GrpcReadinessCheck] failed: UNAVAILABLE: io exception
```

Include failing/timed out check name in health/readiness check response

---

discovery-aws-api/src/main/resources/reference.conf
discovery-aws-api/src/main/scala/akka/discovery/awsapi/ec2/Ec2TagBasedServiceDiscovery.scala
discovery-aws-api/src/main/scala/akka/discovery/awsapi/ecs/EcsServiceDiscovery.scala

By default amazon client uses us-west-1 and at some regions that is far away it may cause very rare issue related to network connectivity.
This may be cause to split brain issue in the cluster when region that is far away from us-west-1 and use auto scaling group.

AWS: Introduced a way to define amazon's endpoint and region

---

cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/LowestAddressJoinDecider.scala

Issue is quite self explanatory - I can't see a good reason to have an important warning log to be disabled by not setting logging level to INFO.
References https://github.com/akka/akka-management/issues/645

Fix LowestAddressJoinDecider cluster formation warning log to not depend on INFO logging level being set

---

docs/src/main/paradox/bootstrap/index.md

This has caused some confusion around the importance of this setting being an exact match, so reference and link to the preference in the overview section.

Reference and link to note on exact match

---

build.sbt
project/Common.scala
project/Dependencies.scala

The scheduled build uses Akka 2.6 and Akka HTTP 10.2 which are not available for Scala 2.11.

build: Scala 2.12 and 2.13 in scheduled build

---

project/Dependencies.scala

That gives us at least Akka Http 10.2.0 coverage until we figure how to fix tests for Akka 2.6.x.

build: disable Akka 2.6 in cron jobs for now

---

docs/src/main/paradox/kubernetes-deployment/preparing-for-production.md

It seems the file name (and the content) for the information on deployment has changed between 2.5 and 2.6(current as of this PR).

doc: link to the recommended Kubernetes deployment setting

---

management/src/main/scala/akka/management/scaladsl/AkkaManagement.scala
project/Dependencies.scala

* `def lookup()` was changed to `def lookup` in `ExtensionIdProvider`
as part of the Scala 2.13.3 update in Akka 2.6.9
References #762

fix compilation error for Akka 2.6.9, #762

---

build.sbt
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/HttpContactPointRoutesSpec.scala
project/Common.scala
project/Dependencies.scala

Maybe it is just me but the structure in `Dependencies` encrypts what dependencies are actually used/available/exported in each module.
This makes the dependencies explicit by less indirection.

Restructure dependencies declaration

---

cluster-bootstrap/src/test/scala/akka/discovery/MockDiscovery.scala
cluster-bootstrap/src/test/scala/akka/management/cluster/bootstrap/contactpoint/ClusterBootstrapDiscoveryBackoffIntegrationSpec.scala

Keep timing separate for the two systems to avoid races

---

lease-kubernetes/src/main/resources/reference.conf
lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/internal/KubernetesApiImpl.scala
lease-kubernetes/src/test/scala/akka/coordination/lease/kubernetes/KubernetesApiSpec.scala

Refs #768
Lazy init of stuff in KubernetesApiImpl depending on a fs read is probably the reason the first test fails.
Additionally made sure response entity is consumed on timeout.

Avoid touching filesystem in test 

---

docs/src/main/paradox/kubernetes-lease.md
lease-kubernetes/lease.yml

* Added a schema
* Tested that leases created with the old CRD work as expected
* Documented touse the fully qualified name as k8s now has its own Lease type

The beta version will be removed in Kubernetes 1.22

---

lease-kubernetes/src/it/scala/akka/coordination/lease/kubernetes/KubernetesApiIntegrationTest.scala
lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/internal/KubernetesApiImpl.scala

The test fails when the first request to the API server times out. So:
* Cancel remaining tests on failure, they are dependent on each other
* Check API server connectivity before starting the tests
Refs #821

Harden KubernetesApiIntegrationSpec

---

cluster-http/src/main/scala/akka/management/cluster/ClusterDomainEventServerSentEventEncoder.scala
cluster-http/src/main/scala/akka/management/cluster/scaladsl/ClusterHttpManagementRoutes.scala
cluster-http/src/test/scala/akka/cluster/http/management/scaladsl/ClusterHttpManagementRoutesSpec.scala
cluster-http/src/test/scala/akka/management/cluster/ClusterDomainEventServerSentEventEncoderSpec.scala
docs/src/main/paradox/cluster-http-management.md

This PR adds a new route to cluster-http, `/cluster/domain-events`, that streams cluster events as Server Sent Events, JSON encoded. Please see the included documentation for route parameters, response format, etc.
ref: #540

cluster-http: Add a route for observing cluster events

---

docs/src/main/paradox/discovery/aws.md
docs/src/main/paradox/discovery/consul.md
docs/src/main/paradox/discovery/kubernetes.md
docs/src/main/paradox/discovery/marathon.md
docs/src/main/paradox/kubernetes-deployment/forming-a-cluster.md

Was not correct for Maven and Gradle in some places, such as https://doc.akka.io/docs/akka-management/current/kubernetes-deployment/forming-a-cluster.html#bootstrap-and-management-dependencies

correction of Scala version in dependencies

---

docs/src/main/paradox/kubernetes-deployment/building-using-maven.md

See https://github.com/akka/akka-platform-guide/pull/543

fix missing SIGTERM: use exec format in docker-maven-plugin

---

cluster-http/src/test/scala/akka/cluster/http/management/scaladsl/ClusterHttpManagementRoutesSpec.scala

Increase patience config

---

cluster-http/src/test/scala/akka/management/cluster/scaladsl/ClusterMembershipCheckSpec.scala

Otherwise:
```
[info] shutting down sbt server
[INFO] [02/25/2021 13:16:16.100] [ClusterHealthCheck-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://ClusterHealthCheck)] Cluster Node [akka.tcp://ClusterHealthCheck@127.0.0.1:59531] - Exiting completed
[INFO] [02/25/2021 13:16:16.100] [ClusterHealthCheck-akka.actor.default-dispatcher-15] [akka.cluster.Cluster(akka://ClusterHealthCheck)] Cluster Node [akka.tcp://ClusterHealthCheck@127.0.0.1:59532] - Exiting completed
[INFO] [02/25/2021 13:16:16.101] [ClusterHealthCheck-akka.actor.default-dispatcher-2] [akka.cluster.Cluster(akka://ClusterHealthCheck)] Cluster Node [akka.tcp://ClusterHealthCheck@127.0.0.1:59531] - Shutting down...
[INFO] [02/25/2021 13:16:16.101] [ClusterHealthCheck-akka.actor.default-dispatcher-15] …
```

Terminate AS otherwise remains in sbt

---

lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/KubernetesLease.scala

Fixes a small issue where a log call wasn't passed any arguments in the lease.

Fix missing lease log args

---

docs/src/main/paradox/kubernetes-deployment/index.md

backport to 1.0 so that we get it out in docs of that release also
(cherry picked from commit 146274dd874b8bc89e3b438300c6d7bf208a6273)

Link to Akka Cloud Platform (backport)

---

.travis.yml

This uses the jabba script from master. This is needed because the
latest release, 0.11.2, has a problem.

Use the latest jabba

---

discovery-aws-api/src/main/mima-filters/1.1.0.backwards.excludes
discovery-aws-api/src/main/resources/reference.conf
discovery-aws-api/src/main/scala/akka/discovery/awsapi/ec2/Ec2TagBasedServiceDiscovery.scala
discovery-aws-api/src/main/scala/akka/discovery/awsapi/ecs/EcsServiceDiscovery.scala
docs/src/main/paradox/discovery/aws.md

AWS module has been stable for quite a while and most if not all actual API is configuration,
by marking a few classed final/methods private I think we can remove the may change marker and
see it as stable.

Remove may-change marker on aws module

---

cluster-http/src/main/mima-filters/1.1.1.backwards.excludes
cluster-http/src/main/scala/akka/management/cluster/ClusterHttpManagementProtocol.scala
cluster-http/src/main/scala/akka/management/cluster/scaladsl/ClusterHttpManagementRoutes.scala
cluster-http/src/test/scala/akka/cluster/http/management/scaladsl/ClusterHttpManagementRoutesSpec.scala
docs/src/main/paradox/cluster-http-management.md

Adds a new route to cluster-http, exposing entity type keys.
From HTTP perspective, output of this route can be provided to
`/cluster/shards/{name}` to programatically grab data.

cluster-http: Expose shard entity type keys

---

lease-kubernetes/src/main/resources/reference.conf
lease-kubernetes/src/test/resources/application.conf
lease-kubernetes/src/test/scala/akka/coordination/lease/kubernetes/KubernetesApiSpec.scala

api-server-request-timeout is 2/5th of lease-operation-timeout
Fixes #937

Give KubernetesApiSpec more time to release the lease

---

docs/src/main/paradox/index.md

The front page of the documentation stated that the current version of Akka Management could be used with either Akka 2.5 or 2.6. I tested this locally, and it does not launch with 2.5, fails with a NoSuchMethodError
References #xxxx

Correct documentation

---

build.sbt
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscovery.scala
lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/internal/KubernetesApiImpl.scala
management-pki/src/main/scala/akka/pki/kubernetes/PemManagersProvider.scala

This PR will load multiple CA certificates from a file provided to the kubernetes api discovery. This is necessary because in case of OpenShift, the cluster will have multiple CAs and the ca.crt file will thus contain multiple certificates.
There are two things I would like to bring up for discussion.
1. Every certificate needs a unique key when added to the trust store. Before this PR the key was the atomic string "cacert". To create a unique key I now append a random string of 6 chars. I don't know if this is the best solution. 
2. The PemManagersProvider is copied from Akka-HTTP. So this PR will introduce a difference to the source in Akka-HTTP. Maybe this issue should also be fixed in Akka-HTTP.
References #947

Load multiple ca certificates from file for kubernetes api discovery

---

cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/contactpoint/HttpClusterBootstrapRoutes.scala

Swapping the order of the `get` and `path` directives in the Cluster Bootstrap routes so that a rejection will prefer 404 Not Found over 405 Method Not Allowed if both method and path are wrong.

Swap order of directives in Cluster Bootstrap

---

.gitignore
docs/src/main/paradox/bootstrap/istio.md

Akka Management/Discovery documentation for Istio was pointing at Akka Classic's mTLS docs. Changed to point to Akka Typed's.

Fixes mTLS link to point to Akka Typed

---

project/Dependencies.scala

Release v1.1.1 is still using logback 1.2.3 which is affect by https://nvd.nist.gov/vuln/detail/CVE-2021-42550
The fix is in v1.2.8, but in the meantime there is already a v1.2.9, so going for it instead.

upgrade logback to 1.2.9

---

cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/SelfAwareJoinDecider.scala

host match will fail in ipv6 environment. Fix it by replace all `[` and `]`.

fix: ipv6 match host

---

cluster-bootstrap/src/main/resources/reference.conf

Adds env var `AKKA_CLUSTER_BOOTSTRAP_PORT_NAME` to specify port name
used in bootstrap.
To be used alongside the existing env var, `AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME`

cluster-bootstrap: Add AKKA_CLUSTER_BOOTSTRAP_PORT_NAME env var

---

docs/src/main/paradox/cluster-http-management.md

Signed-off-by: Al-assad yulin.ying@outlook.com
<br>
The reference to the akka-discovery dependency in the [Cluster Http Management documentation](https://doc.akka.io/docs/akka-management/current/cluster-http-management.html#dependencies) should contains the scala binary version likes `"com.typesafe.akka" %% "akka-discovery" % AkkaVersion`
<br>

Document typos

---

.github/workflows/checks.yml
.github/workflows/integration-tests-maven.yml
.github/workflows/release.yml
.github/workflows/unit-tests.yml
docs/src/main/paradox/index.md
integration-test/kubernetes-api-java/pom.xml
project/Dependencies.scala

* and cleanup of Scala cross building

Akka 2.7.0-M1 dependency

---

.github/workflows/checks.yml
.github/workflows/fossa.yml
.github/workflows/integration-tests-kube-api.yml
.github/workflows/integration-tests-kube-dns.yml
.github/workflows/integration-tests-lease.yml
.github/workflows/integration-tests-maven.yml
.github/workflows/release-drafter.yml
.github/workflows/release.yml
.github/workflows/unit-tests.yml
cluster-http/src/test/scala/akka/cluster/http/management/scaladsl/ClusterHttpManagementRoutesSpec.scala
project/Dependencies.scala

Update to current versions of GH actions before Node 12 is discontinued.
* Replace `olafurpg/setup-scala` with `coursier/setup-action`
* Locking "privately owned" actions to their git hash 
* Current Fossa CLI install URL
* Explicit permissions (see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)
* Upgrade Mockito to 4.9.0 to become JDK17 friendly
Refs https://github.com/akka/akka/pull/31730

chore: renovate GH workflows

---

.scala-steward.conf
project/Dependencies.scala

References https://github.com/lightbend/akka-meta/issues/278

bumping to upgrade scala-xml to 2.1.0

---

.github/workflows/integration-tests-app-version-revision.yml
build.sbt
cluster-bootstrap/src/main/mima-filters/1.3.0.backwards.excludes
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrap.scala
docs/src/main/paradox/rolling-updates.md
integration-test/kubernetes-api-java/pom.xml
integration-test/rollingupdate-kubernetes/kubernetes/akka-cluster-app-value-revision.yml
integration-test/rollingupdate-kubernetes/src/main/scala/akka/cluster/bootstrap/PodDeletionCostDemoApp.scala
integration-test/rollingupdate-kubernetes/test-app-version-revision.sh
integration-test/scripts/app-version-revision-kubernetes-test.sh
rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/AppVersionRevision.scala
rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/KubernetesApi.scala
rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/KubernetesApiImpl.scala
rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/KubernetesJsonSupport.scala
rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/PodDeletionCost.scala
rolling-update-kubernetes/src/test/java/akka/rollingupdate/kubernetes/AppVersionRevisionJavaCompileTest.java
rolling-update-kubernetes/src/test/java/jdoc/akka/rollingupdate/kubernetes/AppVersionRevisionCompileOnly.java
rolling-update-kubernetes/src/test/scala/akka/rollingupdate/kubernetes/AppVersionRevisionSpec.scala
rolling-update-kubernetes/src/test/scala/akka/rollingupdate/kubernetes/PodDeletionCostAnnotatorCrSpec.scala
rolling-update-kubernetes/src/test/scala/doc/akka/rollingupdate/kubernetes/AppVersionRevisionCompileOnly.scala

Todo:
- - https://github.com/akka/akka-management/pull/1145

App version k8s revision

---

integration-test/scripts/rollingupdate-kubernetes-test.sh

Fix https://github.com/akka/akka-management/issues/1148
Easy to reproduce if using a smaller sleep between retries. The list of annotated pods was being carried between attempts leading to issues if not all pods were annotated on the same run.

ci: fix flaky RU kubernetes test

---

cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/ClusterBootstrap.scala
rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/AppVersionRevision.scala
rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/PodDeletionCost.scala

I verified this with the `AppVersionRevision` extension.
Assuming the same for the other two extensions, however I find it strange this did not surface before, for the `ClusterBootstrap` one.

fix: prevent extensions to fail  with cyclic initialization

---

discovery-kubernetes-api/src/main/resources/reference.conf
docs/src/main/paradox/bootstrap/kubernetes-api.md
docs/src/main/paradox/rolling-updates.md

* and for consistency with rolling updates, optionally use the  KUBERNETES_NAMESPACE in kubernetes api discovery

doc: Clarify KUBERNETES_POD_NAME and KUBERNETES_NAMESPACE env variables

---

docs/src/main/paradox/akka-management.md
management/src/main/resources/reference.conf

- replace misspelled `ManagementRoutesProvider` references with the actual class name `ManagementRouteProvider` in docs & reference.conf

Fix references to ManagementRouteProvider

---

integration-test/aws-api-ec2/build.sbt
project/Dependencies.scala

Use same Jackson version as in upcoming Akka 2.9. Targeting next minor release.

bump: Jackson 2.15.2

---

.scala-steward.conf

* the dependency is already on 2.15.2

chore: scala-steward pin Jackson 2.15

---

lease-kubernetes/src/main/resources/reference.conf
lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/KubernetesLease.scala
lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/KubernetesSettings.scala

* for backwards compatibility it's possible to allow old behavior with config, e.g. to support rolling update
Refs #910
Requires a way to define custom lease names, which is added in https://github.com/akka/akka/pull/32122

fix: Fail if too long lease name, #910

---

build.sbt
docs/src/main/paradox/index.md

It currently refers to Akka 2.7, but should say 2.9.
https://doc.akka.io/docs/akka-management/current/index.html

docs: refer to the correct Akka binary version

---

integration-test/scripts/app-version-revision-kubernetes-test.sh

Failed in CI:
```
Error from server (BadRequest): container "akka-rollingupdate-demo" in pod "akka-rollingupdate-demo-7b5c945c65-5hn6c" is waiting to start: ContainerCreating
```
which I think is because we try to get the logs from a pod that is not Running yet

test: Harden Integration Tests for AppVersionRevision

---

.github/workflows/native-image-tests.yml
cluster-bootstrap/src/main/resources/META-INF/native-image/com.lightbend.akka.management/akka-management-cluster-bootstrap/reflect-config.json
cluster-bootstrap/src/main/scala/akka/management/cluster/bootstrap/contactpoint/HttpBootstrapJsonProtocol.scala
cluster-http/src/main/resources/META-INF/native-image/com.lightbend.akka.management/akka-management-cluster-http/reflect-config.json
cluster-http/src/main/scala/akka/management/cluster/ClusterHttpManagementProtocol.scala
discovery-kubernetes-api/src/main/resources/META-INF/native-image/com.lightbend.akka.management/akka-discovery-kubernetes-api/reflect-config.json
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/JsonFormat.scala
docs/src/main/paradox/cluster-jmx-management.md
docs/src/main/paradox/index.md
docs/src/main/paradox/native-image.md
integration-test/dns-api-mesos/build.sbt
integration-test/kubernetes-api-java/pom.xml
lease-kubernetes/src/main/resources/META-INF/native-image/com.lightbend.akka.management/akka-lease-kubernetes/reflect-config.json
lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/internal/KubernetesJsonSupport.scala
management/src/main/resources/META-INF/native-image/com.lightbend.akka.management/akka-management/reflect-config.json
native-image-tests/.gitignore
native-image-tests/build.sbt
native-image-tests/project/build.properties
native-image-tests/project/plugins.sbt
native-image-tests/src/main/resources/application.conf
native-image-tests/src/main/resources/logback.xml
native-image-tests/src/main/scala/com/lightbend/Main.scala
project/Dependencies.scala
rolling-update-kubernetes/src/main/resources/META-INF/native-image/com.lightbend.akka.management/akka-rolling-upgrade-kubernetes/reflect-config.json
rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/KubernetesJsonSupport.scala

Depends on upstream https://github.com/akka/akka/pull/32308 and https://github.com/akka/akka-http/pull/4349 
Test is passing locally, not completely water tight but hopefully good enough, it avoids another CI job on actual k8 which has been a repeated pain.

feat: Native-image metadata and docs

---

management/src/main/scala/akka/management/scaladsl/AkkaManagement.scala

Applying this PR will add the (newer) akka-lease-kubernetes and akka-rolling-update-kubernetes dependencies to the same version check. I think maybe this was missed when the modules were introduced.

Add dependencies to same version check

---

LICENSE
integration-test/dns-api-mesos/build.sbt
integration-test/kubernetes-api-java/pom.xml
native-image-tests/build.sbt
samples/akka-sample-cluster-kubernetes-java/pom.xml
samples/akka-sample-cluster-kubernetes-scala/build.sbt

Refs https://github.com/akka/akka-management/issues/1289
Akka 2.9.3
Akka HTTP 10.6.3 
Samples bumped to 1.5.2 so will not pass
Never mind the branch name, got the version wrong there...

build: License change date for 1.5.2, Akka and HTTP bumps, sample updates

---

.fossa.yml

We don't need FOSSA to scan projects in samples directory, so configure to exclude this directory
References lightbend/akka-meta/issues#488

chore: Exclude samples from FOSSA scanning

---

.gitignore
docs/src/main/paradox/rolling-updates.md
integration-test/rolling-update-kubernetes/src/test/scala/akka/rollingupdate/kubernetes/KubernetesApiIntegrationTest.scala
rolling-update-kubernetes/src/main/resources/reference.conf
rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/KubernetesApiImpl.scala
rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/KubernetesJsonSupport.scala
rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/KubernetesSettings.scala
rolling-update-kubernetes/src/test/scala/akka/rollingupdate/kubernetes/KubernetesApiSpec.scala
rolling-update-kubernetes/src/test/scala/akka/rollingupdate/kubernetes/PodDeletionCostAnnotatorCrSpec.scala
rolling-update-kubernetes/src/test/scala/akka/rollingupdate/kubernetes/PodDeletionCostAnnotatorSpec.scala

References #1302 
Adds a config setting `akka.rollingupdate.kubernetes.revision-annotation` to allow configurability (default is the prior behavior).  From there it's just dealing with Spray JSON.  Admittedly it's been a while (ever?) since I've done Spray JSON trickery, but (with apologies to Tolstoy) "all happy typeclass-and-AST JSON libraries are alike".
I don't have a k8s cluster handy to test, mind.

feat: configurable choice of annotations for rolling update revision

---

discovery-azure-api/src/main/scala/akka/discovery/azureapi/rbac/aks/AzureRbacAksServiceDiscovery.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscovery.scala

It seems like we'd be most interested in the pods which are currently running (cc: @girdharshubham ).  Without this filter, especially in environments where rollouts are frequent (e.g. dev/test environments), there's a chance that getting so many pods could cause HTTP responses which akka http rejects.
Can hide this behind a config setting if needed, but I'm not sure why one would want to discover pods which used to be there.

Only request running pods from Kubernetes API

---

project/Common.scala

As it turns out, this repo was lacking the `-sourcepath` parameter which is used to strip file prefixes when building links to sources in Scaladoc.

docs: link Scaladoc to correct source files

---

discovery-kubernetes-api/src/main/resources/reference.conf
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/KubernetesApiServiceDiscovery.scala
discovery-kubernetes-api/src/main/scala/akka/discovery/kubernetes/Settings.scala
integration-test/lease-kubernetes/src/test/scala/akka/coordination/lease/kubernetes/KubernetesApiIntegrationTest.scala
integration-test/lease-kubernetes/src/test/scala/akka/coordination/lease/kubernetes/LeaseContentionSpec.scala
integration-test/rolling-update-kubernetes/src/test/scala/akka/rollingupdate/kubernetes/KubernetesApiIntegrationTest.scala
lease-kubernetes/src/main/resources/reference.conf
lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/KubernetesLease.scala
lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/KubernetesSettings.scala
lease-kubernetes/src/main/scala/akka/coordination/lease/kubernetes/internal/KubernetesApiImpl.scala
lease-kubernetes/src/test/scala/akka/coordination/lease/kubernetes/KubernetesApiSpec.scala
rolling-update-kubernetes/src/main/resources/reference.conf
rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/KubernetesApiImpl.scala
rolling-update-kubernetes/src/main/scala/akka/rollingupdate/kubernetes/KubernetesSettings.scala
rolling-update-kubernetes/src/test/scala/akka/rollingupdate/kubernetes/KubernetesApiSpec.scala
rolling-update-kubernetes/src/test/scala/akka/rollingupdate/kubernetes/PodDeletionCostAnnotatorCrSpec.scala
rolling-update-kubernetes/src/test/scala/akka/rollingupdate/kubernetes/PodDeletionCostAnnotatorSpec.scala

Fixes #1412
This implements token reload for kubernetes lease coordination. The tokens are loaded as required, and cached for 10 minutes.
10 minutes is selected because kubelet token rotation is done when a token, which by default expires in 1 hour, has reached 80% of its time to live, that is, after 48 minutes.

fix: reload tokens in kubernetes lease
